### ISSUE TITLE
[QUESTION] Support for the new Z2M Symfonisk mode

### ISSUE THREAD

**Issue by mvjt** [xaviml/controllerx#103]
# Question
Your project looks very useful. Thank you! 
Are you planning to implement the new Symfonisk debounce mode of Z2M (legacy=false)?

## Additional information
https://www.zigbee2mqtt.io/devices/E1744.html#legacy-integration

This new mode (legacy=false) makes debounce work properly without flooding with MQTT messages and would make controllerx more efficient.

Essentially, it sends a message when rotation starts, and one when it stops. Instead of flooding with rotation events during rotation. Also, the debounce functionality did not work properly and this has been fixed with legacy: false...

(Sorry a second question)
Why is the Z2M integration depending on a route through Home Assistant ant not directly through MQTT? Wouldn´t this be quicker/smoother?

* Devices involved:
  * IKEA Symfonisk E1744
  * Integration: Choose from `z2m`

**Comment by xaviml** [comment]
Hi @mvjt 

Thank you for your question. ControllerX is not affected by the debounce mode from z2m, it just needs the action form the sensor or from the MQTT. This means you can already benefit from the new debounce mode, however, user is the one that will need to change the z2m configuration to make this happen.

> Why is the Z2M integration depending on a route through Home Assistant ant not directly through MQTT? Wouldn´t this be quicker/smoother?

The first z2m integration was done with the HA sensors for simplicity. However, ControllerX is now also able to connect to MQTT and skip the HA state machine, I have this in my current setup and I noticed a significant speed difference. You will need to change your integration from z2m to mqtt. You can read more about it in [here](https://xaviml.github.io/controllerx/others/integrations#mqtt).

Thanks,

**Comment by mvjt** [comment]
Thanks @xaviml, I believe the action names has changed so I expected Controllerx needed update

Single-click -> toggle
Double-click -> brightness_step_up
Triple-click -> brightness_step_down
Rotate-left -> brighness_move_down and when stop rotating rotating_stop
Rotate-right -> brightness_move_up and when stop rotating rotating_stop

BR

Martin

**Comment by xaviml** [comment]
Hi @mvjt,

Thanks for the information. The code was already updated, but not the documentation, sorry for that. However, could you confirm that the stop rotation is `rotating_stop` and not `brightness_stop` as I have in the code?

Cheers,
Xavi M.

**Comment by mvjt** [comment]
Hi @xaviml,

Sorry it changed again before it hit dev branch. It is brightness_stop, NOT rotating_stop.

**Comment by xaviml** [comment]
I will change the documentation then, however, the code is updated to that already.

Thanks :)

**Comment by mvjt** [comment]
Thanks @xaviml , I also tested it it works perfectly...

Thanks

**Comment by xaviml** [comment]
Documentation has been updated with this information: https://xaviml.github.io/controllerx/controllers/E1744
