### ISSUE TITLE
Add attribute as a parameter for the state integration

### ISSUE THREAD

**Issue by xaviml** [xaviml/controllerx#106]
# Feature Request

### Is your feature request related to a problem?

As of now, the state integration only listen to state changes. However, if the user wants to listen to state attribute changes, he/she is not able to do so.

### Describe the solution / feature you'd like

Add an `attribute` parameter for the `state` integration that is None by default.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by htvekov** [comment]
Hi' @xaviml 

Just a note.
Won't we run into problems with non updating HA sensors, if only attribute changes - but state doesn't ?
Probably not an issue in real life for the kind of sensors that will be used here, but I'm not sure.

I just wasted hours and hours on my display code, trying to template my way out of an explicit entity_id as trigger.
Just to find out that template didn't always update when only attributes changed.

I find the HA documentation a little vague regarding this, so I'm not actually sure if this could give issues later on ?

Ciao !

**Comment by xaviml** [comment]
Hi Henning,

Thank you for your concerns. This new attribute works the same as it is described in AppDaemon: https://appdaemon.readthedocs.io/en/latest/AD_API_REFERENCE.html#appdaemon.adapi.ADAPI.listen_state the `attribute` keyword. According to the documentation it listens to changes on the specific state attribute and not the state itself.

This enhancement does not break anything, it is just an add up to what is already there. By default, it will listen to the state as it was already doing.

Cheers,
Xavi M.

**Comment by htvekov** [comment]
Check, Xavi !

Actually it's a smart move that can eliminate lots of ControllerX code and is a lot more user friendly 👍😃
It's seems that appdeamon is somewhat more dynamic than HA when it comes to states and attributes.
It still eludes me, that you cant use an attribute change on an entity_id as direct trigger in HA, Only way as I understand is to specify a hardcoded entity_id or breakout attributes in seperate sensors.
Not very dynamic, when I need to trigger on attribute changes on first entity_id in a group 🤔

Ciao !
