### ISSUE TITLE
[NEW DEVICE] Tuya TS0043 is also designed as a cover controller

### ISSUE THREAD

**Issue by ChristopheBraud** [xaviml/controllerx#1075]
# New Device Support

## Device Information

- Device Model: TS0043
- Device Description: Tuya TS0043 Cover Remote Controller
- Device Manufacturer: Tuya

## Integrations

_Already integrated as a light controller_

#### Actions

- `1_single`: Cover.OPEN,
- `2_single`: Cover.STOP,
- `3_single`: Cover.CLOSE,

## Image
![image](https://github.com/user-attachments/assets/5fae295e-bb49-4b86-917f-8e6409a00b8b)

**Comment by ChristopheBraud** [comment]
I already wrote and test the code, I'm preparing a PR

**Comment by xaviml** [comment]
This device is now released on [ControllerX v4.28.0](https://github.com/xaviml/controllerx/releases/tag/v4.28.0).
