### ISSUE TITLE
Add color functionality to Muller Licht Remote Control

### ISSUE THREAD

**Issue by ASNNetworks** [xaviml/controllerx#111]
# New Device Support

## Device Information

* Device Model: Tint Remote Control
![71o5enz9xhL _AC_SL1500_](https://user-images.githubusercontent.com/54230480/89781922-8aa32d00-db14-11ea-9827-bd54cdf4521f.jpg)

* Device Description: Remote Control
* Device Manufacturer: Muller Licht

## Integrations

If possible, provide the event mappings for the different actions that can be performed on the controller. Specify the integration.

If you can provide mappings for multiple integrations, copy the section below as many times as needed.

#### Actions

Power button. There is press and release after hold, not hold event.
* `button_color_ring_press: event: 1002
* `button_color_ring_release event: 1002

RGB color ring. The ring consists of multiple areas you can press, but all gave same event. There is press and hold, but both give same event and there is no continous firing. Holding fires event later than press. So works like a delayed press.
* `button_color_ring_press: event: 6002
* `button_color_ring_hold event: 6002

Tint/hue down (left). There is press and hold for continue firing, no separate events for hold and release after hold. Continue firing is not consistent I noticed.
* `button_tint_down_press: event: 4002
* `button_tint_down_hold event: 4002

Tint/hue up (right). There is press and hold for continue firing, no separate events for hold and release after hold. Continue firing is not consistent I noticed.
* `button_tint_up_press: event: 5002
* `button_tint_up_hold event: 5002

Brightness down (left). There is no continuous fire, only press, hold or release after hold. 
* `button_brightness_down_press: event: 3002
* `button_brightness_down_hold event: 3001
* `button_brightness_down_release event: 3003

Brightness up (right). There is no continuous fire, only press, hold or release after hold. 
* `button_brightness_down_press: event: 2002
* `button_brightness_down_hold event: 2001
* `button_brightness_down_release event: 2003

Scene buttons. Only support press events, no hold or double/triple.
* `button_scene_reading_press`: event: 7002
* `button_scene_sunset_press: event: 8002
* `button_scene_party_press: event: 9002
* `button_scene_night_press`: event: 10002
* `button_scene_fire_press: event: 11002
* `button_scene_heart_press: event: 12002
#### Notes

I notice that the hold function of events 4002 and 5002 have some kind of internal counter or bug. For instance: if I continue holding 4002, it wil stop at a point. If I try again, it will not continue fire. If I then press or hold 5002, for 2 or more times events (s not just once) I can again continue firing 4002, until it reaches some kind of limit and then again.

Also the button at the buttom (group button) doesn't work. It also doesn't change the behaviour of the buttons or events (sadly). It has 4 toggles (1, 2, 3 and ALL). BUT if you select ALL, then the remote does not work (nog events fired)

**Comment by ASNNetworks** [comment]
@xaviml thank you for your quick response! So I've fired all events and copy/pasted the JSON's, see below. Also, the group button does not fire off events. Using that button lights up 1 of the 3 leds (or all three together). It doesn;t matter which one is lit up, gives the same events. However, lighting up all three blocks all events entirely.  I think we cannot use that button and it has some functionality for Muller Licht's own devices/hub. 

### **Power button. Only support press events, no hold or double/triple. Releasing after hold give press event**
****`button_color_ring_press: event: 1002****
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 1002
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:46:23.436724+00:00",
    "context": {
        "id": "4c19be5223de4c97ba967d060a110fa6",
        "parent_id": null,
        "user_id": null
    }
}

### **RGB color ring. The ring consists of multiple areas you can press, but all gave same event. There is press and hold, but both give same event and there is no continous firing. Holding fires event later than press. So works like a delayed press.**
**`button_color_ring_press: event: 6002**
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 6002
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:50:37.518400+00:00",
    "context": {
        "id": "1d78b8d073e44c679d5d87e4063420bd",
        "parent_id": null,
        "user_id": null
    }
}

**`button_color_ring_hold event: 6002**
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 6002
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:50:47.771260+00:00",
    "context": {
        "id": "6f9540dd5b0d4ad99408945c48d7a974",
        "parent_id": null,
        "user_id": null
    }
}

### **Tint/hue down (left). There is press and hold for continue firing, no separate events for hold and release after hold. Continue firing is not consistent I noticed.**
**`button_tint_down_press: event: 4002**
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 4002
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:51:10.458637+00:00",
    "context": {
        "id": "14f4804ca33a4e778ca8c3be036f2c93",
        "parent_id": null,
        "user_id": null
    }
}

**`button_tint_down_hold event: 4002**
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 4002
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:51:25.023742+00:00",
    "context": {
        "id": "a7dabdee977d41698731fa98cdfe6add",
        "parent_id": null,
        "user_id": null
    }
}

### **Tint/hue up (right). There is press and hold for continue firing, no separate events for hold and release after hold. Continue firing is not consistent I noticed.**
**`button_tint_up_press: event: 5002**
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 5002
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:51:47.954623+00:00",
    "context": {
        "id": "b9ceb3eedb6a46a997d519f21d551e15",
        "parent_id": null,
        "user_id": null
    }
}

**`button_tint_up_hold event: 5002**
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 5002
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:51:54.257137+00:00",
    "context": {
        "id": "8059a972496844f3bf025dc36fdaf2ff",
        "parent_id": null,
        "user_id": null
    }
}

### **Brightness down (left). There is no continuous fire, only press, hold or release after hold.**
**`button_brightness_down_press: event: 3002**
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 3002
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:52:23.737203+00:00",
    "context": {
        "id": "706540f742924ea8a5b419f2fa5137b4",
        "parent_id": null,
        "user_id": null
    }
}

**`button_brightness_down_hold event: 3001**
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 3001
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:52:56.028886+00:00",
    "context": {
        "id": "695c5dbd31c5424ebfd972de6113c97e",
        "parent_id": null,
        "user_id": null
    }
}

**`button_brightness_down_release event: 3003**
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 3003
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:53:00.426976+00:00",
    "context": {
        "id": "c6ee6ecffef546cc92545d90efccdc76",
        "parent_id": null,
        "user_id": null
    }
}

### **Brightness up (right). There is no continuous fire, only press, hold or release after hold.**
**`button_brightness_down_press: event: 2002**
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 2002
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:53:16.663554+00:00",
    "context": {
        "id": "f96342daa1fb4c2b8b049ce4e47436f7",
        "parent_id": null,
        "user_id": null
    }
}

**`button_brightness_down_hold event: 2001**
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 2001
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:53:40.210503+00:00",
    "context": {
        "id": "ef3d64fd4b9d467ea29086a4086aa940",
        "parent_id": null,
        "user_id": null
    }
}

**`button_brightness_down_release event: 2003**
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 2003
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:53:44.023720+00:00",
    "context": {
        "id": "76b51e61882c4300a3957361caf629eb",
        "parent_id": null,
        "user_id": null
    }
}
### **Scene buttons. Only support press events, no hold or double/triple. Releasing after hold give press event**
**button_scene_reading_press: event: 7002**
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 7002
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:54:32.162839+00:00",
    "context": {
        "id": "4004657f4d3a4d7c8b5212de56f161e2",
        "parent_id": null,
        "user_id": null
    }
}

**`button_scene_sunset_press: event: 8002**
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 8002
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:54:41.445799+00:00",
    "context": {
        "id": "6bb09dac734a4d8eb55aacf72399eff2",
        "parent_id": null,
        "user_id": null
    }
}

**`button_scene_party_press: event: 9002**
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 9002
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:54:46.479257+00:00",
    "context": {
        "id": "bd4a0a98e4194927a3895c0f79b26620",
        "parent_id": null,
        "user_id": null
    }
}

**button_scene_night_press: event: 10002**
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 10002
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:54:52.431053+00:00",
    "context": {
        "id": "9f5a50399668444f8d26f6e4713fe25a",
        "parent_id": null,
        "user_id": null
    }
}

**`button_scene_fire_press: event: 11002**
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 11002
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:54:58.939988+00:00",
    "context": {
        "id": "1b9d7bef68a849f19acde75c793d7346",
        "parent_id": null,
        "user_id": null
    }
}

**`button_scene_heart_press: event: 12002**
{
    "event_type": "deconz_event",
    "data": {
        "id": "zbt_remote_all_rgbw_27",
        "unique_id": "00:15:8d:00:03:8b:f5:ff",
        "event": 12002
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-11T17:55:06.716632+00:00",
    "context": {
        "id": "82a6b26987ce4c1da4db2354ae72afa6",
        "parent_id": null,
        "user_id": null
    }
}

**Comment by xaviml** [comment]
Hi @ASNNetworks,

Thanks for the answer. I will let you know when I look at it closely and what I can integrate in ControllerX.

Cheers,
Xavi M.

**Comment by xaviml** [comment]
This has been released in ControllerX v3.5.0. You can find the details in [here](https://xaviml.github.io/controllerx/controllers/MLI-404011). You will see that some actions were not added since hold actions are not supported for some buttons.

**Comment by hdejongh** [comment]
Hi Xaviml, 

just received this controller.
I noticed that all thought the event for the colour wheel doesn't change the X,Y do change.
Also the angel changes.. Is that something you could work with?

**Comment by hdejongh** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1209

```Pressing or holding the colour wheel results in a Move to Color command. The xy values depend on the last values sent and where on the wheel you press or hold. I think the wheel has four different contacts (let's call them North, East, South, West). Each press "moves" the xy values towards the corresponding point on the CIE 1931 colour space: North: (0.3010, 0.1487) - pink-ish, East: (0.7, 0.3) - red, South: (0.3726, 0.5885) - green-ish, and West: (0.1164, 0.3473) Turquoise-ish. A hold "moves" directly to the corresponding point.
So e.g. to get yellow, hold South for green-ish and then press East to move towards red. There seem to be eight steps between adjacent directions; opposite directions go through an in-between direction: East/West over South; and North/South over East. So a total of 36 different xy values.```

**Comment by xaviml** [comment]
Hi @ASNNetworks,

Could you show me a deCONZ event from HA? So I can see how the angle or XY color is passed through there?

Regards,
Xavi M.

**Comment by hdejongh** [comment]
> 
> 
> Hi @ASNNetworks,
> 
> Could you show me a deCONZ event from HA? So I can see how the angle or XY color is passed through there?
> 
> Regards,
> Xavi M.

i think you mean me:) I'll get it for you shortly.

**Comment by xaviml** [comment]
Yes, sorry.. haha I got the name of the OP instead of yours.. it was meant to you @hdejongh 

Thanks,

**Comment by hdejongh** [comment]
ok i did 12 presses:
3 right (top)
3 down
3 left
3 up

and those correspond with (top to down) :

```
{
    "event_type": "deconz_event",
    "data": {
        "id": "woonkamer_muller",
        "unique_id": "00:15:8d:00:03:8c:85:f9",
        "event": 6002,
        "device_id": "e0c57b047dd4131016d2c96eb92466c9",
        "angle": 330,
        "xy": [
            0.12,
            0.08
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-01-05T09:19:15.881897+00:00",
    "context": {
        "id": "acf49a248098275501f740009f276e12",
        "parent_id": null,
        "user_id": null
    }
}

Event 10 fired 10:19 AM:

{
    "event_type": "deconz_event",
    "data": {
        "id": "woonkamer_muller",
        "unique_id": "00:15:8d:00:03:8c:85:f9",
        "event": 6002,
        "device_id": "e0c57b047dd4131016d2c96eb92466c9",
        "angle": 320,
        "xy": [
            0.1191,
            0.1431
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-01-05T09:19:14.930966+00:00",
    "context": {
        "id": "3d2bd97686fa5e20112d208dde3b8d41",
        "parent_id": null,
        "user_id": null
    }
}

Event 9 fired 10:19 AM:

{
    "event_type": "deconz_event",
    "data": {
        "id": "woonkamer_muller",
        "unique_id": "00:15:8d:00:03:8c:85:f9",
        "event": 6002,
        "device_id": "e0c57b047dd4131016d2c96eb92466c9",
        "angle": 310,
        "xy": [
            0.1184,
            0.1974
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-01-05T09:19:14.306160+00:00",
    "context": {
        "id": "4e4ec70c0da41c9f42e56a0caa13d336",
        "parent_id": null,
        "user_id": null
    }
}

Event 8 fired 10:19 AM:

{
    "event_type": "deconz_event",
    "data": {
        "id": "woonkamer_muller",
        "unique_id": "00:15:8d:00:03:8c:85:f9",
        "event": 6002,
        "device_id": "e0c57b047dd4131016d2c96eb92466c9",
        "angle": 300,
        "xy": [
            0.1178,
            0.2436
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-01-05T09:19:10.240688+00:00",
    "context": {
        "id": "e7d5576debdf86118b8d515b0931daa4",
        "parent_id": null,
        "user_id": null
    }
}

Event 7 fired 10:19 AM:

{
    "event_type": "deconz_event",
    "data": {
        "id": "woonkamer_muller",
        "unique_id": "00:15:8d:00:03:8c:85:f9",
        "event": 6002,
        "device_id": "e0c57b047dd4131016d2c96eb92466c9",
        "angle": 310,
        "xy": [
            0.1184,
            0.1974
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-01-05T09:19:09.505563+00:00",
    "context": {
        "id": "885d2e0631874c33c6168e3b78555853",
        "parent_id": null,
        "user_id": null
    }
}

Event 6 fired 10:19 AM:

{
    "event_type": "deconz_event",
    "data": {
        "id": "woonkamer_muller",
        "unique_id": "00:15:8d:00:03:8c:85:f9",
        "event": 6002,
        "device_id": "e0c57b047dd4131016d2c96eb92466c9",
        "angle": 320,
        "xy": [
            0.1191,
            0.1431
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-01-05T09:19:09.089144+00:00",
    "context": {
        "id": "b0ae9a633fc13825f0293eed0c1cfdec",
        "parent_id": null,
        "user_id": null
    }
}

Event 5 fired 10:19 AM:

{
    "event_type": "deconz_event",
    "data": {
        "id": "woonkamer_muller",
        "unique_id": "00:15:8d:00:03:8c:85:f9",
        "event": 6002,
        "device_id": "e0c57b047dd4131016d2c96eb92466c9",
        "angle": 330,
        "xy": [
            0.12,
            0.08
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-01-05T09:19:04.353807+00:00",
    "context": {
        "id": "83c6dad920396861735854fcdcfe838e",
        "parent_id": null,
        "user_id": null
    }
}

Event 4 fired 10:19 AM:

{
    "event_type": "deconz_event",
    "data": {
        "id": "woonkamer_muller",
        "unique_id": "00:15:8d:00:03:8c:85:f9",
        "event": 6002,
        "device_id": "e0c57b047dd4131016d2c96eb92466c9",
        "angle": 340,
        "xy": [
            0.1951,
            0.1085
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-01-05T09:19:03.714423+00:00",
    "context": {
        "id": "619a15a59d34bf8da54cc3da1a69c5c1",
        "parent_id": null,
        "user_id": null
    }
}

Event 3 fired 10:19 AM:

{
    "event_type": "deconz_event",
    "data": {
        "id": "woonkamer_muller",
        "unique_id": "00:15:8d:00:03:8c:85:f9",
        "event": 6002,
        "device_id": "e0c57b047dd4131016d2c96eb92466c9",
        "angle": 350,
        "xy": [
            0.2543,
            0.1309
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-01-05T09:19:03.144791+00:00",
    "context": {
        "id": "d86e313c23b50bcbe0024bb50c757995",
        "parent_id": null,
        "user_id": null
    }
}

Event 2 fired 10:18 AM:

{
    "event_type": "deconz_event",
    "data": {
        "id": "woonkamer_muller",
        "unique_id": "00:15:8d:00:03:8c:85:f9",
        "event": 6002,
        "device_id": "e0c57b047dd4131016d2c96eb92466c9",
        "angle": 0,
        "xy": [
            0.301,
            0.1487
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-01-05T09:18:52.866692+00:00",
    "context": {
        "id": "2f2abe43663e3f6d0e2115b591c9ebcd",
        "parent_id": null,
        "user_id": null
    }
}

Event 1 fired 10:18 AM:

{
    "event_type": "deconz_event",
    "data": {
        "id": "woonkamer_muller",
        "unique_id": "00:15:8d:00:03:8c:85:f9",
        "event": 6002,
        "device_id": "e0c57b047dd4131016d2c96eb92466c9",
        "angle": 0,
        "xy": [
            0.301,
            0.1487
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-01-05T09:18:52.168318+00:00",
    "context": {
        "id": "4307225fc417de9a320b9efc9f32b5ad",
        "parent_id": null,
        "user_id": null
    }
}

Event 0 fired 10:18 AM:

{
    "event_type": "deconz_event",
    "data": {
        "id": "woonkamer_muller",
        "unique_id": "00:15:8d:00:03:8c:85:f9",
        "event": 6002,
        "device_id": "e0c57b047dd4131016d2c96eb92466c9",
        "angle": 0,
        "xy": [
            0.301,
            0.1487
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-01-05T09:18:51.544072+00:00",
    "context": {
        "id": "ac16be055b8b137f57f8ba47b804b364",
        "parent_id": null,
        "user_id": null
    }
}
```

**Comment by xaviml** [comment]
Thanks @hdejongh for the answer. I will reopen this ticket, and change the title. There are some internal changes that need to happen to implement this, so it won't be straight away.

Regards,
Xavi M.

**Comment by hdejongh** [comment]
how about i send you a remote which you can keep so you can test it your self?
Do you also have a conbee2 stick?

**Comment by xaviml** [comment]
Hi @hdejongh,

Thank you for the offering. I am happy if you are able to test this functionality once I release some beta versions. I have a way of developing this in an easy way and I am confident in developing it without the need of the controller itself.

Thanks again and very kind of you :)
Xavi M.

**Comment by hdejongh** [comment]
np i would love to test!
To bad the lowest button doesnt do anything (i see no events popping up in HA)

**Comment by xaviml** [comment]
Hi @hdejongh,

ControllerX v4.4.0b0 will be released in 5-10 minutes from now. It ships this functionality. It reads the deconz event to get the xy color when pressing the color wheel (6002 event).

You can toggle "Show beta" in HACS to get this release.

Regards,
Xavi M.

**Comment by hdejongh** [comment]
downloading!

**Comment by hdejongh** [comment]
Did you create a default mapping or should i do that? cause nothing happens when i press the ring...

**Comment by xaviml** [comment]
I did add it to the default mapping. Did you restart AppDaemon addon after updating?

**Comment by xaviml** [comment]
Check AppDaemon logs for errors or warning if possible as well. Thank you :)

**Comment by hdejongh** [comment]
restarted HA, no joy for the ring.

**Comment by xaviml** [comment]
What do you see in the AppDaemon logs when pressing the ring?

**Comment by hdejongh** [comment]
there are no appdaemon logs:)

**Comment by hdejongh** [comment]
log:
  logfile: /config/appdaemon/appdaemon.log
  errorfile: /config/appdaemon/appdaemon.log
  
that's probably wrong...

**Comment by xaviml** [comment]
How did you install AppDaemon? Was it through the addon? If so, you can go to the addon and click to the "Logs" tab you will see on the top (if you are in a computer). You will see a "refresh" button that you can use to refresh the logs.

**Comment by hdejongh** [comment]
stupid me doing 2 things at the same time. I actually looked already here a couple of days ago while using a debug log feature in our app:). I added the log_level

Woonkamer_Muller:
  log_level: DEBUG
  module: controllerx
  class: MLI404011LightController
  controller: woonkamer_muller
  integration: deconz
  light: light.lg_woonkamer

2021-01-05 20:24:13.027549 DEBUG Woonkamer_Muller: Calling listen_event for Woonkamer_Muller
2021-01-05 20:24:39.580425 DEBUG Woonkamer_Muller: 🎮 Button event triggered, but not registered: `6002`
2021-01-05 20:24:40.909180 DEBUG Woonkamer_Muller: 🎮 Button event triggered, but not registered: `6002`
2021-01-05 20:26:42.733265 DEBUG Woonkamer_Muller: 🎮 Button event triggered, but not registered: `6002`
2021-01-05 20:26:43.036370 DEBUG Woonkamer_Muller: 🎮 Button event triggered, but not registered: `6002`

**Comment by xaviml** [comment]
No worries, I assumed you knew where to find the logs, my fault. Thank you for adding the debug log as well. I see that it does not recognize the 6002 event. When initializing AppDaemon, do you see something like:

`INFO Woonkamer_Muller: 🎮 ControllerX v4.4.0b0`

Regards,

**Comment by xaviml** [comment]
I just saw your message:

> restarted HA, no joy for the ring.

You need to restart AppDaemon addon, not Home Assistant.

**Comment by hdejongh** [comment]
ok it works but if you press multiple times on the same spot the color keeps changing... 
it's like its cycling through all colours which are between so lets say you click "right" which is red (and i first have to click it around 10 times before it becomes red). and then you click left light blue it will first go yellow then green and than blue....

so its not instant...

**Comment by xaviml** [comment]
Thank you for reporting back with logs.

I see that the xy_color is not consistent even when pressing right (red) multiple times. Could you check in "Developer Tools > Events", then start listening for `deconz_event`. Once listening for the event, could you click consistenly to the same spot and report in here what you see? I would like to see if the controller is reporting the same xy_color.

**Comment by hdejongh** [comment]
i already did that this afternoon. in my initial post: https://github.com/xaviml/controllerx/issues/111#issuecomment-754514376
3 times same spot...

ill try multiple times again cause i think eventually it will stay the same color

**Comment by hdejongh** [comment]
ok tried it again, if you keep pressing the same spot multiple times then eventually it stops changing the xy_color. but that can take over. if i go from bottom to top it will take at least 20 presses to reach the final (correct) color...
Angle shows it aswell. lets say i click left as soon as the event shows 90 i will have reach the right color.
down is 180, left is 270 up is 0. so 360 degrees...

**Comment by xaviml** [comment]
I missed that, sorry. I see now that the only consistent one is when clicking up multiple times, but for the rest, the xy color seems to be random.

The only thing I did in ControllerX was to read that xy color and use light.on service by passing `xy_color` attribute with the value from the deconz event. You can try it manually from Developer Tools, and see if you get the same colors.

**Comment by hdejongh** [comment]
not really random its always connected the angle..
i pressed so many times the battery's are already empty:)

**Comment by hdejongh** [comment]
Oh!!! it needs to be a long press! if you do a long press its working fine. short press will just add "10 degrees" and keep doing that until you reach the right color

**Comment by hdejongh** [comment]
yes only one time

**Comment by xaviml** [comment]
So is everything working fine? Let me know if you find anything not working properly. I will release the v4.4.0 in a couple of days.

**Comment by hdejongh** [comment]
yes its working fine, but the remote isn't very high quality... so its kinda hard to select the right color.
But your script works flawless many thanks!

**Comment by xaviml** [comment]
Color ring functionality has been added to ControllerX [v4.4.0](https://github.com/xaviml/controllerx/releases/tag/v4.4.0).
