### ISSUE TITLE
Existing device, now with deconz support -> WXCJKG13LM (Aqara)

### ISSUE THREAD

**Issue by ASNNetworks** [xaviml/controllerx#117]
# New Device Support

## Device Information

* Device Model: WXCJKG13LM 
* Device Description: WXCJKG13LMLightController (Light)
* Device Manufacturer: Aqara

## Integrations

If possible, provide the event mappings for the different actions that can be performed on the controller. Specify the integration.

If you can provide mappings for multiple integrations, copy the section below as many times as needed.

#### Actions
I copy/pasted the Zigbee2MQTT mappings from your website and replaced them with deconz events.

1002 🠖 Single click top left button
1004 🠖 Double click top left button
1005 🠖 Double triple top left button
1001 🠖 Hold top left button
1003 🠖 Release top left button
2002 🠖 Single click top right button
2004 🠖 Double click top right button
2005 🠖 Double triple top right button
2001 🠖 Hold top right button
2003 🠖 Release top right button
3002 🠖 Single click middle left button
3004 🠖 Double click middle left button
3005 🠖 Double triple middle left button
3001 🠖 Hold middle left button
3003 🠖 Release middle left button
4002 🠖 Single click middle right button
4004 🠖 Double click middle right button
4005 🠖 Double triple middle right button
4001 🠖 Hold middle right button
4003 🠖 Release middle right button
5002 🠖 Single click bottom left button
5004 🠖 Double click bottom left button
5005 🠖 Double triple bottom left button
5001 🠖 Hold bottom left button
5003 🠖 Release bottom left button
6002 🠖 Single click bottom right button
6004 🠖 Double click bottom right button
6005 🠖 Double triple bottom right button
6001 🠖 Hold bottom right button
6003 🠖 Release bottom right button

#### Notes

(Optional) Additional notes for the integration, eg. known bugs, issues or limitations of the device for the specified integration.

**Comment by xaviml** [comment]
Hi @ASNNetworks,

Thank you for this information. I will be adding this device for next release.

Cheers,
Xavi M.

**Comment by xaviml** [comment]
This has been released in ControllerX v3.5.0. You can find the details in [here](https://xaviml.github.io/controllerx/controllers/WXCJKG13LM).
