### ISSUE TITLE
Existing device, now with deconz support -> Double key wireless (Aqara) WXKG02LM Rev.2

### ISSUE THREAD

**Issue by cpuks** [xaviml/controllerx#142]
# New Device Support

## Device Information

* Device Model: WXKG02LM Rev.2
* Device Description: WXKG02LMLight
* Device Manufacturer: Aquara

## Integrations

If possible, provide the event mappings for the different actions that can be performed on the controller. Specify the integration.

If you can provide mappings for multiple integrations, copy the section below as many times as needed.

#### Actions

1002 🠖 single left
1001 🠖 long left
1004 🠖 double left
2002 🠖 single right
2001 🠖 long right
2004 🠖 double right
3002 🠖 single both
3001 🠖 long both
3004 🠖 double both

#### Notes

(Optional) Additional notes for the integration, eg. known bugs, issues or limitations of the device for the specified integration.

**Comment by xaviml** [comment]
Hi @cpuks,

Thanks for opening this ticket. I will integrate this Controller for the next release.

Cheers,
Xavi M.

**Comment by xaviml** [comment]
This has been added to ControllerX v4.0.0b1. Let me know if this works as expected.

**Comment by xaviml** [comment]
This has been added to ControllerX v4.0.0.
