### ISSUE TITLE
Existing device, now with deconz support -> WXKG01LM (Aqara)

### ISSUE THREAD

**Issue by cpuks** [xaviml/controllerx#143]
# New Device Support

## Device Information

* Device Model: WXKG01LM
* Device Description: WXKG01LMLight
* Device Manufacturer: Aquara

## Integrations

If possible, provide the event mappings for the different actions that can be performed on the controller. Specify the integration.

If you can provide mappings for multiple integrations, copy the section below as many times as needed.

#### Actions

1002 🠖 single
1004 🠖 double
1005 🠖 triple
1006 🠖 quadruple
1010 🠖 five
1003 🠖 hold the button
1000 🠖 release the button

#### Notes

(Optional) Additional notes for the integration, eg. known bugs, issues or limitations of the device for the specified integration.

**Comment by xaviml** [comment]
Hi @cpuks,

Thank you for opening the ticket, I will be integrating this controller for the next release.

Cheers,
Xavi M.

**Comment by xaviml** [comment]
This has been added to ControllerX v4.0.0b1. Let me know if this works as expected.

Cheers,
Xavi M.

**Comment by xaviml** [comment]
This has been added to ControllerX v4.0.0.
