### ISSUE TITLE
[NEW DEVICE] Osram Lightify Switch Mini

### ISSUE THREAD

**Issue by bobbynobble** [xaviml/controllerx#153]
# New Device Support

## Device Information

* Device Model: [ AC0251100NJ / AC0251400NJ / AC0251600NJ / AC0251700NJ ] (different models are just different colours)
* Device Description: [ Lightify Switch Mini ]
* Device Manufacturer: [ Osram ]

## Integrations

If possible, provide the event mappings for the different actions that can be performed on the controller. Specify the integration.

If you can provide mappings for multiple integrations, copy the section below as many times as needed.

#### Actions

* `on`: Sent when button 1 is pressed
* `move_with_on_off`: Sent when button 1 is held
* `stop`: Sent when button 1 is released after hold
* `move_to_level_with_on_off`: Sent when button 2 is pressed
* `move_to_color_temp`: Sent when button 2 is released after press
* `move_to_saturation`: Sent when button 2 is held
* `move_hue`: Sent when button 2 is released after hold
* `off`: Sent when button 3 is pressed
* `move`: Sent when button 3 is held
* `stop`: Sent when button 3 is released after hold

On long release, buttons 1 and 3 both send the same "stop" command but the endpoints are different. All button 1 commands are endpoint 1, all button 3 are endpoint 2 and all button 2 are endpoint 3.

#### Notes

(Optional) Additional notes for the integration, eg. known bugs, issues or limitations of the device for the specified integration.

Button 1 is up arrow
Button 2 is circle
Button 3 is down arrow

Factory settings:
Button 1 short press: ON
Button 1 long press: Brightness up
Button 2 short press: 2700K / Brightness 100%
Button 2 long press: Change color (forward)
Button 3 short press: OFF
Button 3 long press: Brightness DOWN

**Comment by xaviml** [comment]
Hi @bobbynobble,

This is great, is all that I need to integrate the controller. Could you maybe also send an example of payload, the JSON object you see from Developer Tools when listening to zha_event?

One day ZHA will start sending more self-explanatory actions than things like `move_hue` for when the second button is released. Lucky me you described the action, otherwise it would have been impossible for me to guess.

Since I have a function where I can change the actions, I might do something like:
"endpoint"+"command", so the stop actions will be: "1_stop" and "2_stop".

Cheers,
Xavi M.

**Comment by bobbynobble** [comment]
Morning @xaviml 

That's great to hear, thank you. 

Payload below for a short press on each of the three buttons, just shout if you'd like anymore...

Button 1 short press (think these might happen on release but there is only one command so assume it doesn't matter)
```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:0d:6f:00:10:82:b4:38",
        "unique_id": "00:0d:6f:00:10:82:b4:38:1:0x0006",
        "endpoint_id": 1,
        "cluster_id": 6,
        "command": "on",
        "args": []
    },
    "origin": "LOCAL",
    "time_fired": "2020-10-16T07:18:02.366516+00:00",
    "context": {
        "id": "ba2c5ff80f7f11eb94896988e316726f",
        "parent_id": null,
        "user_id": null
    }
}
```

Button 2 short press
```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:0d:6f:00:10:82:b4:38",
        "unique_id": "00:0d:6f:00:10:82:b4:38:3:0x0008",
        "endpoint_id": 3,
        "cluster_id": 8,
        "command": "move_to_level_with_on_off",
        "args": [
            254,
            10
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2020-10-16T07:17:58.267225+00:00",
    "context": {
        "id": "b7badf8b0f7f11ebbbf59d70279d93cc",
        "parent_id": null,
        "user_id": null
    }
}
```

Button 2 short press on release
```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:0d:6f:00:10:82:b4:38",
        "unique_id": "00:0d:6f:00:10:82:b4:38:3:0x0300",
        "endpoint_id": 3,
        "cluster_id": 768,
        "command": "move_to_color_temp",
        "args": [
            370,
            10
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2020-10-16T07:17:59.263741+00:00",
    "context": {
        "id": "b852edf80f7f11eb9f984df91022afb1",
        "parent_id": null,
        "user_id": null
    }
}
```

Button 3 short press (again, think it happens on release)
```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:0d:6f:00:10:82:b4:38",
        "unique_id": "00:0d:6f:00:10:82:b4:38:2:0x0006",
        "endpoint_id": 2,
        "cluster_id": 6,
        "command": "off",
        "args": []
    },
    "origin": "LOCAL",
    "time_fired": "2020-10-16T07:17:53.454898+00:00",
    "context": {
        "id": "b4dc92070f7f11ebb0c61dac0b04a167",
        "parent_id": null,
        "user_id": null
    }
}
```

**Comment by xaviml** [comment]
This controller has been added to ControllerX v4.1.0 :) Check out device page [here](https://xaviml.github.io/controllerx/controllers/OSRAM-AC025XX00NJ).

**Comment by bobbynobble** [comment]
Thank you so much, will try it out later.

**Comment by bobbynobble** [comment]
Works perfectly, thanks again.
