### ISSUE TITLE
E1743 controller buttons reversed on 2.1.0 in deconz

### ISSUE THREAD

**Issue by fribse** [xaviml/controllerx#17]
Hi @xaviml 

So HA 0.104.3, ControllerX 2.1.0.
Deconz integration.

Buttons for Controller E1743 from IKEA are reversed.

**Comment by xaviml** [comment]
Sorry @fribse,

Which actions are reversed? When turning on/off and/or dimming the light?

Thank you!

**Comment by xaviml** [comment]
What does the "I" and "O" button do? I have a ConBee device getting delivered, but I don't have it yet. This is why I am asking for  current mapping.

**Comment by fribse** [comment]
Well normally the I is on / brighten and O is off / dim.
In 2.1.0:
The I will turn off for short press, and dim for long press.
The O will turn on for short press, and brighten for long press.

So, the buttons are completely reversed 😆 
No need to apologize @xaviml , that's what happens during development.

**Comment by xaviml** [comment]
Hey @fribse 

This should be fixed now on the v2.1.1. Thanks for your collaboration!

**Comment by fribse** [comment]
NP, I'll test when I get home :-)

**Comment by fribse** [comment]
And I've now moved three more from IKEA to deconz, and the controllers works perfectly!
