### ISSUE TITLE
[BUG] Colour temp cycles infinitely when using emulated colour temp (color_wheel: color_temp_wheel)

### ISSUE THREAD

**Issue by wafliron** [xaviml/controllerx#172]
# Bug report

## Description

I'm not clear whether this is a bug or if I'm requesting a new feature - but went with bug.

I have a number of Ikea Tradfri Bulb E27 bulbs (Ikea ID 104.086.16) that natively support RGB colour but don't natively support setting a colour temperature.

Using color_wheel: color_temp_wheel, ControllerX is able to emulate colour temperature support for these bulbs, and I'm able to use the actions click_color_down / click_color_up / hold_color_down / hold_color_up to cycle through the emulated colour temp range.

However, when using these actions the colour temp cycles infinitely - e.g. once the light reaches it's maximum (bluest) emulated colour temp, if I click / keep holding the applicable button on the remote the light will cycle back all the way back to it's minimum (reddest) colour temp and then progressively start getting bluer again (and vice versa when decreasing the colour temp). As opposed to when using a light with native colour temp support and [click|hold]_colortemp_[up|down] actions, where the light's colour temp will stop changing once the max / min value is reached.

[click|hold]_colortemp_[up|down] doesn't work with these bulbs (elicits no response) even with color_wheel: color_temp_wheel in the setup, only [click|hold]_color_[up|down].

## Additional information

* Devices involved:
  * IKEA 1810 as Controller
  * IKEA Tradfri Bulb E27 600lm RGB (Ikea ID 104.086.16) as Light
* Integration: zha
* AppDaemon version: v0.3.1
* ControllerX version: v4.1.0
* HACS version (if installed from there): v1.6.0
* Home Assistant Core version:  0.116.4

## AppDaemon app configuration

```controller_rgbonly_colourtemptest:
  module: controllerx
  class: E1810Controller
  controller: xxxxxx
  integration: zha
  # Behaves the same if the color_mode: attribute is excluded
  light:
    name: light.test_rgbonly_light
    color_mode: xy_color
  smooth_power_on: false
  multiple_click_delay: 300
  manual_steps: 5
  delay: 10
  color_wheel: color_temp_wheel
  merge_mapping:
    press_257_13_0: click_color_down              # Left arrow - click
    press_256_13_0: click_color_up                # Right arrow - click
    hold_3329_0: hold_color_up                    # Left arrow - hold
    hold_3328_0: hold_color_down                  # Right arrow - hold
```

## Logs

N/A I believe, but let me know if need anything.

## Additional Context

Nothing, but let me know if need any other info.

**Comment by xaviml** [comment]
Hi @wafliron,

As mentioned in #171, this is the expected behaviour, since the `color_temp_wheel` is just a predefined color_wheel that anyone can use. Per definition, the color wheels cycle infinitely, they do not have min and max. I kept #171 open, in favor of adding a proper color_temp emulation for xy_color lights.

Regards,
Xavi M.
