### ISSUE TITLE
No events showing for IKEA on/off switch with ZHA integration

### ISSUE THREAD

**Issue by MysticNynja** [xaviml/controllerx#178]
# Question

I have an Ikea On/off Switch hooked up through ZHA.  I don't see any entities in that device except for the battery. How do I get this to work as a switch? It says the button is IDLE in AppDaemon.  I don't get any events in Home Assistant when I listen for "zha_event".  I used Tasmota on a Sonoff Zigbee Bridge. I see the switch in the AppDaemon UI under Entities.  

## Additional information

* Devices involved:
  * Model: IKEA E1743
* Integration: Choose from `zha`
* AppDaemon version:4.0.5
* ControllerX version: 4.1.0
* HACS version (if installed from there): 1.6.2
* Home Assistant Core version: 0.117.6

## AppDaemon app configuration
office_plug:
  module: controllerx
  class: E1743SwitchController
  controller: <controller ID from Integration Page>
  integration: zha
  switch: switch.snf_plug2

**Comment by xaviml** [comment]
Hi @MysticNynja,

First thing I would be trying to figure out is why listening to "zha_event" doesn't work. So if you go to "Developer Tools > Events" , type "zha_event" in the "Listen to events" section, start listening, and then press any button from your controller. Do you see any events popping up in the screen? If not, your controller has not been correctly configured probably. Could you then check your ZHA devices from Home Assistant Configuration if the device is in there? And probably try unbinding and binding the device again.

If you are still not able to see the anything, here are a couple of issues related to this in Home Assistant core:
- https://github.com/home-assistant/core/issues/31734
- https://github.com/home-assistant/core/issues/36484

Regards,
Xavi M.

**Comment by MysticNynja** [comment]
I will check those out.  My button was not showing in as a "zha_event" and right now I have uninstalled everything and am reinstalling.  I'll check those related issues and post an update when I can.  

Thanks!

**Comment by xaviml** [comment]
This issue will remain closed since it does not seem to be related to ControllerX. Happy to keep helping out with the issue in this thread.
