### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by EPMatt** [xaviml/controllerx#19]
It would be nice to create issue templates for better managing and organizing bug reports and feature requests in the future.

The different issue types could be: 

- Bug report
- New device support
- Feature request

Each of the templates would include info regarding the specific issue e.g. for New device support type we could include a placeholder for device name, device manufacturer and mappings for the controller.

@xaviml if you think that's a good idea I'd be happy to help with it and work on the templates.

**Comment by xaviml** [comment]
This is a good idea, I was thinking about it recently. I will create them and I will let you know about it. Thanks @EPMatt

**Comment by EPMatt** [comment]
You're welcome @xaviml!
We can keep the issue open so we can talk later about this improvement here. :)
Thanks a lot!

**Comment by xaviml** [comment]
You can check the templates now, let me know what you think, we can change them if needed. The config files are in .github/ISSUE_TEMPLATES. I close this issue. Thanks!

**Comment by EPMatt** [comment]
Hi @xaviml,
the templates are great! Managing issues should be much easier now.
Maybe we could add more details so user can provide as much info as they can, especially on the New Device issue type. I'll make a PR with the proposed changes.
Thank you so much!

**Comment by xaviml** [comment]
Thanks @EPMatt!
