### ISSUE TITLE
Ikea Tradfri Remote Only Turns Off, Not On

### ISSUE THREAD

**Issue by JasperMC** [xaviml/controllerx#194]
Hello there!

Big fan of ControllerX. I'm using a ConBee II and Home Assistant with a Tradfri Remote Control (the one with brightness and cool white/warm white adjustment buttons)

This works really well, but since two days ago I can only use the power button to turn off a group of lights, but not on. My partner and I use it as a main switch for our living room, so we use it a lot.

I haven't changed anything in my configuration/setup so I'm curious as to why this is happening.

Technical setup:

Intel nuc running everything in docker:
- appdaemon
- homeassistant
- deconz

**Comment by xaviml** [comment]
Hi @jaspercardol,

Sorry to hear about that. I will try to help you as much as I can :)

Could you please also share:
- the controllerx config in apps.yaml
- AppDaemon logs when the lights are off and you click to the button to turn them on?

Also, is it only a problem when turning it on? Or do the other button stop working as well?

Finally, do you remember what has it changed these past 2 days? For example:
- New update from deCONZ?
- Upgrading ControllerX (by the way, which version are you using?)
- New version of AppDaemon?
- New version of Home Assistant?

Regards,
Xavi M.

**Comment by JasperMC** [comment]
Hello @xaviml,

The issue seems to have resolved itself the next day. I still have no idea what happened. Will report back if it happens again, maybe it is some kind of bug after all.

For now, this can be closed :)
