### ISSUE TITLE
ZHA integration for WXCJKG12LM

### ISSUE THREAD

**Issue by WiktorBuczko** [xaviml/controllerx#202]
# New Device Support

## Device Information

* Device Model: WXCJKG12LM
* Device Description: Aqara Opple Wireless Switch 4 Button
* Device Manufacturer: Aqara

#### Actions

1_single → Single click top left button
1_double → Double click top left button
1_triple → Triple click top left button
1_long press → Hold top left button
1_release → Release top left button
and similar for rest of the buttons
#### Notes

event for single click 
```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "04:cf:8c:df:3c:75:c3:22",
        "unique_id": "04:cf:8c:df:3c:75:c3:22:1:0x0012",
        "device_id": "4450c8f12b9fe73c8dab26fd3309afd8",
        "endpoint_id": 1,
        "cluster_id": 18,
        "command": "1_single",
        "args": {
            "button": 1,
            "press_type": "single",
            "attr_id": 85,
            "value": 1
        }
    },
    "origin": "LOCAL",
    "time_fired": "2020-12-16T19:45:16.541025+00:00",
    "context": {
        "id": "ea498c6334e5139a751524493467c13b",
        "parent_id": null,
        "user_id": null
    }
}
```
double click
```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "04:cf:8c:df:3c:75:c3:22",
        "unique_id": "04:cf:8c:df:3c:75:c3:22:1:0x0012",
        "device_id": "4450c8f12b9fe73c8dab26fd3309afd8",
        "endpoint_id": 1,
        "cluster_id": 18,
        "command": "1_double",
        "args": {
            "button": 1,
            "press_type": "double",
            "attr_id": 85,
            "value": 2
        }
    },
    "origin": "LOCAL",
    "time_fired": "2020-12-16T19:58:13.987316+00:00",
    "context": {
        "id": "90d7302b0af051ee937b2b6d1eae58c3",
        "parent_id": null,
        "user_id": null
    }
}
```
triple click
```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "04:cf:8c:df:3c:75:c3:22",
        "unique_id": "04:cf:8c:df:3c:75:c3:22:1:0x0012",
        "device_id": "4450c8f12b9fe73c8dab26fd3309afd8",
        "endpoint_id": 1,
        "cluster_id": 18,
        "command": "1_triple",
        "args": {
            "button": 1,
            "press_type": "triple",
            "attr_id": 85,
            "value": 3
        }
    },
    "origin": "LOCAL",
    "time_fired": "2020-12-16T19:58:39.577297+00:00",
    "context": {
        "id": "22645b581acd65ed2f52abc05c8ece0a",
        "parent_id": null,
        "user_id": null
    }
}
```
hold
```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "04:cf:8c:df:3c:75:c3:22",
        "unique_id": "04:cf:8c:df:3c:75:c3:22:1:0x0012",
        "device_id": "4450c8f12b9fe73c8dab26fd3309afd8",
        "endpoint_id": 1,
        "cluster_id": 18,
        "command": "1_long press",
        "args": {
            "button": 1,
            "press_type": "long press",
            "attr_id": 85,
            "value": 0
        }
    },
    "origin": "LOCAL",
    "time_fired": "2020-12-16T19:45:18.402484+00:00",
    "context": {
        "id": "8c057f7848abd2c41a55ec21497bf6ea",
        "parent_id": null,
        "user_id": null
    }
}
```
release
```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "04:cf:8c:df:3c:75:c3:22",
        "unique_id": "04:cf:8c:df:3c:75:c3:22:1:0x0012",
        "device_id": "4450c8f12b9fe73c8dab26fd3309afd8",
        "endpoint_id": 1,
        "cluster_id": 18,
        "command": "1_release",
        "args": {
            "button": 1,
            "press_type": "release",
            "attr_id": 85,
            "value": 255
        }
    },
    "origin": "LOCAL",
    "time_fired": "2020-12-16T19:45:19.228985+00:00",
    "context": {
        "id": "a3bb7608b9a8060dedcd275268b6f27c",
        "parent_id": null,
        "user_id": null
    }
}
```

I have added this device to apps.yaml but I am getting this error when I click any button so I assume it is not supported yet.
`2020-12-16 20:58:39.611511 WARNING opple_salon_salon_test: ------------------------------------------------------------
2020-12-16 20:58:39.614278 WARNING opple_salon_salon_test: Unexpected error in worker for App opple_salon_salon_test:
2020-12-16 20:58:39.617608 WARNING opple_salon_salon_test: Worker Ags: {'id': '1188bfd08a844897bd3b46a21998ebfa', 'name': 'opple_salon_salon_test', 'objectid': '9e749dce7f39455e9e1a1c9aead54d3f', 'type': 'event', 'event': 'zha_event', 'function': <bound method ZHAIntegration.callback of <cx_core.integration.zha.ZHAIntegration object at 0x7571f538>>, 'data': {'device_ieee': '04:cf:8c:df:3c:75:c3:22', 'unique_id': '04:cf:8c:df:3c:75:c3:22:1:0x0012', 'device_id': '4450c8f12b9fe73c8dab26fd3309afd8', 'endpoint_id': 1, 'cluster_id': 18, 'command': '1_triple', 'args': {'button': 1, 'press_type': 'triple', 'attr_id': 85, 'value': 3.0}}, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'device_ieee': '04:cf:8c:df:3c:75:c3:22', '__thread_id': 'MainThread'}}
2020-12-16 20:58:39.620396 WARNING opple_salon_salon_test: ------------------------------------------------------------
2020-12-16 20:58:39.624314 WARNING opple_salon_salon_test: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 838, in async_worker
    await funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/controllerx/cx_core/integration/zha.py", line 36, in callback
    action = self.get_action(data)
  File "/config/appdaemon/apps/controllerx/cx_core/integration/zha.py", line 23, in get_action
    args = args["args"]
KeyError: 'args'
2020-12-16 20:58:39.626765 WARNING opple_salon_salon_test: ----------------------------------------------------------—`
I do not have the 2 or 6 button version but I assume integrating them will be similar

**Comment by xaviml** [comment]
Hi @WiktorBuczko,

Indeed, this controller is not yet supported for ZHA. I will add it for the next release. I assume that there are actions for the rest if the buttons like:

X_single → Single click top left button
X_double → Double click top left button
X_triple → Triple click top left button
X_long press → Hold top left button
X_release → Release top left button 

where X goes from 1 to 6, correct?

Also, how did you try to add this controller to ZHA? I am surprised on the error is showing you. It should be showing a clear error message that the controller is not supported for zha I believe.

Regards,
Xavi M.

**Comment by WiktorBuczko** [comment]
Yes, those actions are correct. 
Indeed, when I was using class: WXCJKG12LMLightController in configuration, I got the message "ValueError: This controller does not support zha" but when I changed it to "class: LightController" I got that error. I thought I can get this to work using custom controller. Thank you very much. 😊

**Comment by xaviml** [comment]
I see. You were doing well, normally there is no need of integrating a controller to make it work. The controller integration is just to define a default mapping, but in the case of ZHA since their input action vary a lot depending on the controller, it could be the case that it needs to be added so it can be used.

This is the case for this Controller since the default parse function for ZHA does not seem to work for it. Sorry for the inconvenience.

I will keep you updated with the addition of the controller.

Cheers,
Xavi M.

**Comment by xaviml** [comment]
ZHA support has been added to this controller in ControllerX [v4.3.0](https://github.com/xaviml/controllerx/releases/tag/v4.3.0)
