### ISSUE TITLE
IKEA 1766 z2m

### ISSUE THREAD

**Issue by oscfor** [xaviml/controllerx#214]
# New Device Support

## Device Information

* Device Model: E1766
* Device Description: TRADFRI open/close remote
* Device Manufacturer: IKEA

## Integrations

If possible, provide the event mappings for the different actions that can be performed on the controller. Specify the integration.

If you can provide mappings for multiple integrations, copy the section below as many times as needed.

#### Actions

MQTT discovery data:
Topic: homeassistant/device_automation/0x680ae2fffe6fd574/action_close/config

MQTT discovery data:
Topic: homeassistant/device_automation/0x680ae2fffe6fd574/click_close/config

MQTT discovery data:
Topic: homeassistant/device_automation/0x680ae2fffe6fd574/action_stop/config

MQTT discovery data:
Topic: homeassistant/device_automation/0x680ae2fffe6fd574/click_release/config

MQTT discovery data:
Topic: homeassistant/device_automation/0x680ae2fffe6fd574/action_open/config

MQTT discovery data:
Topic: homeassistant/device_automation/0x680ae2fffe6fd574/click_open/config

#### Notes

(Optional) Additional notes for the integration, eg. known bugs, issues or limitations of the device for the specified integration.

**Comment by xaviml** [comment]
Hi @oscfor,

Thank you for opening this ticket. I understand that you want to add support for Z2M to E1766 controller. Is that right? If so, I will need the value of the following topic `zigbee2mqtt/0x680ae2fffe6fd574/action` which shown in Z2M logs when clicking the controller. I believe that this controller just supports open and close actions. This is what I get when clicking the middle button from the E1810 IKEA controller:

```
Zigbee2MQTT:info  2021-01-03 20:31:50: MQTT publish: topic 'zigbee2mqtt/livingroom_controller/action', payload 'toggle'
```

Regards,
Xavi M.

**Comment by oscfor** [comment]
Hi @xaviml,

Thank you for creating such a great app! 

Yes, support for 1766 is exactly what I am looking for. 

payload 'open'
payload 'close'

is what I get from action and click.

Regards
Oscar

**Comment by xaviml** [comment]
Hi @oscfor,

Thank you for the reply. I will add those actions to the existings E1766 controllers for the Z2M integration.

Regards,
Xavi M.

**Comment by xaviml** [comment]
Hi @oscfor,

Could you confirm if this device with Z2M also fires an event when released after being held? For deCONZ and ZHA, this controller support:
- open: 1 click up
- close: 1 click down
- stop: fired after bing held

Regards,
Xavi M.

**Comment by oscfor** [comment]
You are correct!

INFO: MQTT publish: topic 'zigbee2mqtt/katarina_switch_rullgardin/action', payload 'stop'
INFO: MQTT publish: topic 'zigbee2mqtt/katarina_switch_rullgardin/click', payload 'release'

It comes from both directions when you hold and release.

**Comment by xaviml** [comment]
Thank you @oscfor, the `click` one is deprecated from Zigbee2MQTT and it will be removed in the future, so I will add the `stop`.

**Comment by xaviml** [comment]
Support for this device with Z2M has been added to ControllerX [v4.4.0](https://github.com/xaviml/controllerx/releases/tag/v4.4.0).
