### ISSUE TITLE
Osram Smart+ Mini / Lightify Mini

### ISSUE THREAD

**Issue by doemer** [xaviml/controllerx#231]
# New Device Support

## Device Information

Device Model: Lightify Mini AC025XX00NJ
Osram Smart+ Mini
Device Manufacturer: Osram/LEDVance

## Integrations

Integration:  deconz

Click Arrow up -> 1002
Hold Arrow Up -> 1001
Release Arrow Up -> 1003
Click Arrow down -> 2002
Hold Arrow down -> 2001
Release Arrow down -> 2003
Click Circle button -> 3002
Hold Circle button -> 3001
Release Circle button -> 3003

#### Notes

I hope this is all you need to add deconz as well for this type of Switch. Thx a lot for all your effort!!

**Comment by xaviml** [comment]
Device added in [ControllerX v4.5.0](https://github.com/xaviml/controllerx/releases/tag/v4.5.0).
