### ISSUE TITLE
Add `mute` as a predefined action for Media Players

### ISSUE THREAD

**Issue by xaviml** [xaviml/controllerx#238]
# Feature Request

### Is your feature request related to a problem?

If I want to mute my media player, I need to use a service call for it.

### Describe the solution / feature you'd like

The solution is to add a new [predefined action](https://xaviml.github.io/controllerx/advanced/predefined-actions) for the `mute` action.

### Describe alternatives you've considered

Use a service call

### Additional context

Request comes from [here](https://github.com/xaviml/controllerx/issues/78#issuecomment-770301725).

**Comment by xaviml** [comment]
This predefined action has been added to ControllerX [v4.6.0](https://github.com/xaviml/controllerx/releases/tag/v4.6.0)

**Comment by lensherm** [comment]
> This predefined action has been added to ControllerX [v4.6.0](https://github.com/xaviml/controllerx/releases/tag/v4.6.0)

Thank you very much @xaviml !
