### ISSUE TITLE
[NEW DEVICE] Lonsonho Tuya ZigBee Wireless Smart Scene Switch 4 Gang

### ISSUE THREAD

**Issue by dummys** [xaviml/controllerx#240]
Hi, It is possible to add this device: https://github.com/Koenkk/zigbee2mqtt/issues/4468 ?
It's already supported in Zigbee2MQTT but it could be nice to have it inside controllerX, as it is a nice 4 buttons switch.

**Comment by xaviml** [comment]
Hi @dummys,

Could you please provide the fired events when: pressing, double (triple, quatriple, etc.. if supported) pressing, holding, and release? I would need to know all the possible events fired from this controller for each of the buttons, so I can map them and give support for this controller. It is not clear to me from the ticket you attached the possible actions.

Thank you,
Xavi M.

**Comment by xaviml** [comment]
I will add this device according to the following documentation: https://www.zigbee2mqtt.io/devices/TS0044.html

**Comment by xaviml** [comment]
This device has been added to [ControllerX v4.10.0](https://github.com/xaviml/controllerx/releases/tag/v4.10.0).
