### ISSUE TITLE
[NEW DEVICE] WXKG11LMSensorSwitchLightController with Deconz

### ISSUE THREAD

**Issue by schneekluth** [xaviml/controllerx#257]
This [device](https://xaviml.github.io/controllerx/controllers/WXKG11LM-sensor_switch) is currently only usable with ZHA but works fine with Deconz too. Please find the Deconz events and corresponding clicks in the table below.

## Device Information

- Device Model: WXKG11LM (lumi.sensor_switch.aq2 - Aqara)
- Device Description: Aqara Button (Variant with up to 4 clicks
- Device Manufacturer: [ Aqara ]

#### Actions

|  Deconz Event  | Action    |
|:--------------- |--------- |
| 1002                  | 1 click    |
| 1004                  | 2 clicks  |
| 1005                  | 3 clicks  |
| 1006                  | 4 clicks |

#### Notes
Reference: https://xaviml.github.io/controllerx/controllers/WXKG11LM-sensor_switch

**Comment by xaviml** [comment]
Hi @schneekluth,

Thank you for opening this ticket. The mapping is now added to the dev branch, so it will be available for the next release.

Regards,
Xavi M.

**Comment by xaviml** [comment]
This controller has been added to ControllerX [v4.8.0](https://github.com/xaviml/controllerx/releases/tag/v4.8.0).
