### ISSUE TITLE
[BUG] different types of lights in ons group

### ISSUE THREAD

**Issue by laurens1989** [xaviml/controllerx#26]
**Describe the bug**

I use a Ikea round dimmer for my kitchen lights, 4 off the same type of light bulb and this works fine.

Now I had 2 new lights bulbs in the living room e14 and e27, whit the smal dimmer. They works fine in ha and I can dim the lights together whit a light card entetie . The switch works fine on both lamps, but when I group the lights I can only set them on and off.

Is this right of are I am doing  somting wrong.

_Device_: 
_Integration_: Choose from `z2m`
_Logs (if applicable)_:

**Comment by xaviml** [comment]
Hi,

I will be able to help you better if you answer the following questions:

1. What is the configuration for it from apps.yaml
2. Which controller are you using?
3. Can you specify which lights you are grouping together (link from supported devices from zigbee2mqtt.io)

Thanks,

**Comment by laurens1989** [comment]
1: What is the configuration for it from apps.yaml
eetkamer_Controller:      << This one works fine
  module: controllerx
  class: E1810Controller
  controller: sensor.0x14b457fffe45eabf_action
  integration: z2m
  light: light.kitchen_lights

Kamer_Lamp:       << The one that only can switch on/off
  module: controllerx
  class: E1743Controller
  controller: sensor.kleine_dimmer_kamer_click
  integration: z2m
  light: light.Kamer_Lamp

2. Which controller are you using?
See one.

3.Can you specify which lights you are grouping together (link from supported devices from zigbee2mqtt.io)

4x https://www.zigbee2mqtt.io/devices/LED1732G11.html - works totaly fine ( on the switch eetkamer_Controller)

https://www.zigbee2mqtt.io/devices/LED1836G9.html
https://www.zigbee2mqtt.io/devices/LED1649C5.html
group together and link to Kamer_Lamp.

**Comment by laurens1989** [comment]
sorry my bad!! the problem are the light groups, now i set a normal group."name op lights" and link to the controller and dimming works fine! thank for your fast response and great app for HA

**Comment by xaviml** [comment]
Yes, that is right, you were using [this](https://www.home-assistant.io/integrations/light.group/) platform instead of using the regular [integration](https://www.home-assistant.io/integrations/group/). I have to take a look if I can give support to grouped lights with the light group platform, but that is not planned yet.
