### ISSUE TITLE
[BUG] E1743 Dimmer control

### ISSUE THREAD

**Issue by StudioShemp** [xaviml/controllerx#268]
Controllerx: 4.8.0
HA: 2021.3.4
Appdaemon 4: 0.5.1 HA Build
Z2M: 1.6.0

I have an Ikea E1743 controller controlling a light which previously would perform on/off/brightness up and brightness down. 

Recently the brightness up/down stopped working through controllerx (still working via lovelace)

The app is unchanged and looks like this:

diningroom_light:
  module: controllerx
  class: E1743Controller
  controller: sensor.0xec1bbdfffec45114_click
  integration: z2m
  light: light.dininglight

The Appdaemon logs look fine for the on/off functions but for Brightness I see this (up held first, then down):

2021-04-02 23:34:24.144556 INFO diningroom_light: 🏃 Running `Predefined (release)` now
2021-04-02 23:34:24.134503 INFO diningroom_light: 🎮 Button event triggered: `brightness_stop`
2021-04-02 23:34:21.084482 INFO diningroom_light: 🏃 Running `Predefined (release)` now
2021-04-02 23:34:21.075202 INFO diningroom_light: 🎮 Button event triggered: `brightness_stop`
2021-04-02 23:34:15.604398 INFO diningroom_light: 

I'm seeing nothing in the Error log (empty).

I'd appreciate your help/advice!

**Comment by xaviml** [comment]
Hi @StudioShemp,

The `_click` is deprecated from zigbee2mqtt. Instead the use of the `_action` is recommended, so you should have a sensor called `sensor.0xec1bbdfffec45114_action`, which you could replace in the `controller` attribute.

Let me know if this fixes your problem.

Regards,
Xavi M.

**Comment by StudioShemp** [comment]
Thanks so much for getting back to me so quickly.

With _action I see this:
diningroom_light: diningroom_light: Entity sensor.0xec1bbdfffec45114_action not found in namespace default

I also don't see a sensor listed for this switch in Entities under Appdaemon with sensor.0xec1bbdfffec45114_action suffix 

- but sensor.0xec1bbdfffec45114_click is there. 
Honestly I really appreciate your help - but I don't want you to put too much priority on it now - this can wait until after Easter!

**Comment by xaviml** [comment]
No worries, I have some time now. I would like to understand first where the problem, because I think it is related to a missmatch of the actions from the controller.

Could you maybe share in here the zigbee2mqtt logs when holding/ releasing up/down?

It is interesting that you do not have the _action sensor. Could you also share all the entities (through Developer Tools in HA) that contain "0xec1bbdfffec45114"?

Thanks! And happy easter :)

**Comment by StudioShemp** [comment]
Thanks, and to you.

here are the entities from Developer tools:

sensor.0xec1bbdfffec45114_battery | 34 | battery: 34 linkquality: 23 click:  unit_of_measurement: % friendly_name: TradfriOnOffSw1_battery device_class: battery
-- | -- | --
sensor.0xec1bbdfffec45114_click |   | battery: 34 linkquality: 23 click:  friendly_name: TradfriOnOffSw1_click icon: mdi:toggle-switch
sensor.0xec1bbdfffec45114_linkquality | 23 | battery: 34 linkquality: 23 click:  unit_of_measurement: - friendly_name: TradfriOnOffSw1_linkquality

Sorry - the table didn't paste well.

And Z2M
  zigbee2mqtt:info 4/3/2021, 12:17:29 AM MQTT publish: topic 'zigbee2mqtt/TradfriOnOffSw1', payload '{"battery":34,"linkquality":10,"click":"brightness_up"}'
  zigbee2mqtt:info 4/3/2021, 12:17:29 AM MQTT publish: topic 'zigbee2mqtt/TradfriOnOffSw1', payload '{"battery":34,"linkquality":10,"click":""}'
  zigbee2mqtt:info 4/3/2021, 12:17:30 AM MQTT publish: topic 'zigbee2mqtt/TradfriOnOffSw1', payload '{"battery":34,"linkquality":10,"click":"brightness_stop"}'
  zigbee2mqtt:info 4/3/2021, 12:17:30 AM MQTT publish: topic 'zigbee2mqtt/TradfriOnOffSw1', payload '{"battery":34,"linkquality":10,"click":""}'

 TradfriOnOffSw1 being the alias for the same device.

Maybe the best action may be deleting and re-pairing, to see if the _action function appears?

Cheers,
Alan

**Comment by StudioShemp** [comment]
I should also say thanks for your great work on controllerx. Before I discovered it, my Hue dimmer scripts were the bane of my life!

**Comment by StudioShemp** [comment]
Hi,

Your mention that _click was deprecated led me to find the following in the Z2M documentation:


> Deprecated click event #
> By default this device exposes a deprecated click event. It’s recommended to use the action event instead.
> 
> To disable the click event, set legacy: false for this device in configuration.yaml. Example:
> 
> devices:
>   '0x12345678':
>     friendly_name: my_device
>     legacy: false

I'll try that in the morning (it's nearly 1am here) but looking very much like I can get rid of the legacy _click behaviour and expose _action.

**Comment by StudioShemp** [comment]
OK, so I made the change under devices: in zigbee2mqtt so te entry now reads

> '0xec1bbdfffec45114':
>   friendly_name: TradfriOnOffSw1
>   retain: false
>   legacy: false

I'm still not seeing an _action event on the device - the z2m logs show (for physical button presses off, on, brightness up, brightness down)
  zigbee2mqtt:info 4/3/2021, 3:24:47 PM MQTT publish: topic 'zigbee2mqtt/TradfriOnOffSw1', payload '{"battery":16,"linkquality":31,"click":"off"}'
  zigbee2mqtt:info 4/3/2021, 3:24:47 PM MQTT publish: topic 'zigbee2mqtt/TradfriOnOffSw1', payload '{"battery":16,"linkquality":31,"click":""}'
  zigbee2mqtt:info 4/3/2021, 3:24:49 PM MQTT publish: topic 'zigbee2mqtt/TradfriOnOffSw1', payload '{"battery":11,"linkquality":31}'
  zigbee2mqtt:info 4/3/2021, 3:24:49 PM MQTT publish: topic 'zigbee2mqtt/TradfriOnOffSw1', payload '{"battery":11,"linkquality":31,"click":"on"}'
  zigbee2mqtt:info 4/3/2021, 3:24:49 PM MQTT publish: topic 'zigbee2mqtt/TradfriOnOffSw1', payload '{"battery":11,"linkquality":31,"click":""}'
  zigbee2mqtt:info 4/3/2021, 3:24:51 PM MQTT publish: topic 'zigbee2mqtt/TradfriOnOffSw1', payload '{"battery":16,"linkquality":31}'
  zigbee2mqtt:info 4/3/2021, 3:24:52 PM MQTT publish: topic 'zigbee2mqtt/TradfriOnOffSw1', payload '{"battery":16,"linkquality":31,"click":"brightness_up"}'
  zigbee2mqtt:info 4/3/2021, 3:24:52 PM MQTT publish: topic 'zigbee2mqtt/TradfriOnOffSw1', payload '{"battery":16,"linkquality":31,"click":""}'
  zigbee2mqtt:info 4/3/2021, 3:24:53 PM MQTT publish: topic 'zigbee2mqtt/TradfriOnOffSw1', payload '{"battery":16,"linkquality":34,"click":"brightness_stop"}'
  zigbee2mqtt:info 4/3/2021, 3:24:53 PM MQTT publish: topic 'zigbee2mqtt/TradfriOnOffSw1', payload '{"battery":16,"linkquality":34,"click":""}'

and in the Appdaemon log
2021-04-03 15:24:53.867738 INFO diningroom_light: 🏃 Running `Predefined (release)` now
2021-04-03 15:24:53.859491 INFO diningroom_light: 🎮 Button event triggered: `brightness_stop`
2021-04-03 15:24:49.644313 INFO diningroom_light: 

🤖 Service: [1mlight.turn_on[0m
  - entity_id: light.dininglight
2021-04-03 15:24:49.631929 INFO diningroom_light: 🏃 Running `Predefined (on)` now
2021-04-03 15:24:49.623449 INFO diningroom_light: 🎮 Button event triggered: `on`
2021-04-03 15:24:47.604069 INFO diningroom_light: 

🤖 Service: [1mlight.turn_off[0m
  - entity_id: light.dininglight
2021-04-03 15:24:47.592854 INFO diningroom_light: 🏃 Running `Predefined (off)` now
2021-04-03 15:24:47.583915 INFO diningroom_light: 🎮 Button event triggered: `off`

Perhaps it's a delete and re-pair that's required from MQTT and Z2M.

One thing I have noticed is that Appdaemon logs the hold and the release actions for my Philips controllers, but against the Tradfri E1743 I see only the Stop, and not the Brightness Up or Down action, but they do show in the Z2M logs.

I'll try the delete and re-pair in Z2M next.

Cheers
StudioShemp

**Comment by xaviml** [comment]
Hi @StudioShemp,

Thank you for all the updates and the details. I see that you are running Zigbee2MQTT 1.6.0, rrleased in 2019. Latest version is 1.18.1. Probably in the version you are using the `click` is not yet deprecated, and action does not yet appear.

Is there a reason you are still running 1.6.0?

Regards,
Xavi M.

**Comment by StudioShemp** [comment]
Hi,

Thanks for highlighting that. Under Supervisor it's not showing as update available, so I assumed I had the latest version. Clearly that's not the case and I have a fair bit of catching up to do.

I'll dig in to that and figure out why it's not up to date, then hopefully it will just work. Happy to close this one.

Thanks so much for your help.
StudioShemp

**Comment by xaviml** [comment]
Hi @StudioShemp,

Happy to help further if needed :) But I am pretty sure that your problem will be solved when you upgrade zigbee2mqtt. That is because the `*_click` action releases `brightness_up` and `brightness_down` (as you shown). And the `*_action` releases `brightness_move_up` and `brightness_move_down`, which are the action in the default mapping for E1743 in ControllerX.

While you figure out how to upgrade z2m, you can get your controller working with _click sensor with the following configuration:

```yaml
diningroom_light:
  module: controllerx
  class: E1743Controller
  controller: sensor.0xec1bbdfffec45114_click
  integration: z2m
  light: light.dininglight
  merge_mapping:
    brightness_up: hold_brightness_up
    brightness_down: hold_brightness_down
```

Regards,
Xavi M.

**Comment by StudioShemp** [comment]
Sorted following a manual update of zigbee2mqtt and re-pairing all devices- thanks so much for your assistance and sorry for the hassle- all working as expected.

StudioShemp
