### ISSUE TITLE
High CPU usage even not using ControllerX

### ISSUE THREAD

**Issue by jd1900** [xaviml/controllerx#278]
After installing ControllerX in HACS the CPU usage of AppDaemon bumps from around 3-4% to 14% permanently. 
I'm not even using ControllerX yet, just installing it.

**Comment by xaviml** [comment]
Hi @jd1900,

This comment might help you:  https://community.home-assistant.io/t/controllerx-bring-full-functionality-to-light-and-media-player-controllers/148855/898

AppDaemon checks periodically for file changes if production mode is not set.

I will add this to the FAQ, so other can read about it.

Regards,
Xavi M.

**Comment by jd1900** [comment]
Thank you @xaviml , it did the trick!
This should be in the https://github.com/hassio-addons/addon-appdaemon rather than in your FAQ, but adding it there will hopefully help some users as well.

**Comment by xaviml** [comment]
Not sure where it should be placed since the CPU usage goes high because ControllerX has many files to track. But I will try to create a PR for the addon documentation and see if we can get it to be merged.

Cheers,
