### ISSUE TITLE
Is it possible to use HueSmartButton with z2m?

### ISSUE THREAD

**Issue by flipkoester** [xaviml/controllerx#284]
# Question

Is it possible to use HueSmartButton as z2m and not as deconz integration?

## Additional information

* Devices involved:
  * Model: HueSmartButtonLightController as [ Light ]
* Integration: z2m

**Comment by flipkoester** [comment]
Sorry. Thanks Christian

**Comment by xaviml** [comment]
Hi @flipkoester,

There is support for deconz as of now for this controller, but I will add support to this controller following the actions I found in the zigbee2mqtt page of this device: https://www.zigbee2mqtt.io/devices/8718699693985.html

Cheers,
Xavi M.

**Comment by xaviml** [comment]
Hi @flipkoester ,

By looking at the z2m documentation I see the following actions are available for this controller: "on, off, skip_backward, skip_forward, press, hold, release". Is this true? This seems to much, I am expecting:
- single press
- hold
- release

The same as deconz integration. Could you please provide the mapping you see in the zigbee2mqtt logs?

Cheers,

**Comment by xaviml** [comment]
I will proceed to close this ticket for lack of information. It can be reopened if more information is provided.

**Comment by oscfor** [comment]
Hi @xaviml 

This button stopped working for me with version 4.20.

Push 
Info 2022-05-31 15:53:27MQTT publish: topic 'zigbee2mqtt/matsalsdimmer', payload '{"action":"press","battery":100,"linkquality":87,"update":{"state":"idle"},"update_available":null}'
Info 2022-05-31 15:53:27MQTT publish: topic 'zigbee2mqtt/matsalsdimmer', payload '{"action":"","battery":100,"linkquality":87,"update":{"state":"idle"},"update_available":null}'
Info 2022-05-31 15:53:27MQTT publish: topic 'zigbee2mqtt/matsalsdimmer/action', payload 'press'
Info 2022-05-31 15:53:27MQTT publish: topic 'zigbee2mqtt/matsalsdimmer', payload '{"action":"release","battery":100,"linkquality":83,"update":{"state":"idle"},"update_available":null}'
Info 2022-05-31 15:53:27MQTT publish: topic 'zigbee2mqtt/matsalsdimmer', payload '{"action":"","battery":100,"linkquality":83,"update":{"state":"idle"},"update_available":null}'
Info 2022-05-31 15:53:27MQTT publish: topic 'zigbee2mqtt/matsalsdimmer/action', payload 'release'
Info 2022-05-31 15:53:27MQTT publish: topic 'zigbee2mqtt/matsalsdimmer', payload '{"action":"off","battery":100,"linkquality":87,"update":{"state":"idle"},"update_available":null}'
Info 2022-05-31 15:53:27MQTT publish: topic 'zigbee2mqtt/matsalsdimmer', payload '{"action":"","battery":100,"linkquality":87,"update":{"state":"idle"},"update_available":null}'
Info 2022-05-31 15:53:27MQTT publish: topic 'zigbee2mqtt/matsalsdimmer/action', payload 'off'


Push and hold
Info 2022-05-31 15:46:08MQTT publish: topic 'zigbee2mqtt/matsalsdimmer', payload '{"action":"press","battery":100,"linkquality":91,"update":{"state":"idle"},"update_available":null}'
Info 2022-05-31 15:46:08MQTT publish: topic 'zigbee2mqtt/matsalsdimmer', payload '{"action":"","battery":100,"linkquality":91,"update":{"state":"idle"},"update_available":null}'
Info 2022-05-31 15:46:08MQTT publish: topic 'zigbee2mqtt/matsalsdimmer/action', payload 'press'
Info 2022-05-31 15:46:09MQTT publish: topic 'zigbee2mqtt/matsalsdimmer', payload '{"action":"skip_backward","battery":100,"linkquality":87,"step_size":30,"transition_time":9,"update":{"state":"idle"},"update_available":null}'
Info 2022-05-31 15:46:09MQTT publish: topic 'zigbee2mqtt/matsalsdimmer', payload '{"action":"","battery":100,"linkquality":87,"update":{"state":"idle"},"update_available":null}'
Info 2022-05-31 15:46:09MQTT publish: topic 'zigbee2mqtt/matsalsdimmer/action', payload 'skip_backward'
Info 2022-05-31 15:46:09MQTT publish: topic 'zigbee2mqtt/matsalsdimmer', payload '{"action":"hold","battery":100,"linkquality":91,"update":{"state":"idle"},"update_available":null}'
Info 2022-05-31 15:46:09MQTT publish: topic 'zigbee2mqtt/matsalsdimmer', payload '{"action":"","battery":100,"linkquality":91,"update":{"state":"idle"},"update_available":null}'
Info 2022-05-31 15:46:09MQTT publish: topic 'zigbee2mqtt/matsalsdimmer/action', payload 'hold'
Info 2022-05-31 15:46:10MQTT publish: topic 'zigbee2mqtt/matsalsdimmer', payload '{"action":"skip_backward","battery":100,"linkquality":87,"step_size":56,"transition_time":9,"update":{"state":"idle"},"update_available":null}'
Info 2022-05-31 15:46:10MQTT publish: topic 'zigbee2mqtt/matsalsdimmer', payload '{"action":"","battery":100,"linkquality":87,"update":{"state":"idle"},"update_available":null}'
Info 2022-05-31 15:46:10MQTT publish: topic 'zigbee2mqtt/matsalsdimmer/action', payload 'skip_backward'
Info 2022-05-31 15:46:10MQTT publish: topic 'zigbee2mqtt/matsalsdimmer', payload '{"action":"hold","battery":100,"linkquality":87,"update":{"state":"idle"},"update_available":null}'
Info 2022-05-31 15:46:10MQTT publish: topic 'zigbee2mqtt/matsalsdimmer', payload '{"action":"","battery":100,"linkquality":87,"update":{"state":"idle"},"update_available":null}'
Info 2022-05-31 15:46:10MQTT publish: topic 'zigbee2mqtt/matsalsdimmer/action', payload 'hold'
Info 2022-05-31 15:46:10MQTT publish: topic 'zigbee2mqtt/matsalsdimmer', payload '{"action":"release","battery":100,"linkquality":83,"update":{"state":"idle"},"update_available":null}'
Info 2022-05-31 15:46:10MQTT publish: topic 'zigbee2mqtt/matsalsdimmer', payload '{"action":"","battery":100,"linkquality":83,"update":{"state":"idle"},"update_available":null}'
Info 2022-05-31 15:46:10MQTT publish: topic 'zigbee2mqtt/matsalsdimmer/action', payload 'release'
Info 2022-05-31 15:46:12MQTT publish: topic 'zigbee2mqtt/Källartrappa aktivitet', payload

**Comment by xaviml** [comment]
Hi @oscfor ,

Could you please:
- Create a new ticket for this issue
- Add your ControllerX configuration
- Add AppDaemon logs
- If you use HACS for ControllerX installation, could you please go back to 4.19.0 and confirm that is working there?

Thanks!

**Comment by oscfor** [comment]
> 

- Of course. Added here https://github.com/xaviml/controllerx/issues/498

- matsalsdimmer:
  module: controllerx
  class: HueSmartButtonLightController
  controller: zigbee2mqtt/matsalsdimmer/action
  integration: mqtt
  light: light.matsal_taklampa

- 2022-05-31 20:07:19.001967 WARNING matsalsdimmer: ------------------------------------------------------------
2022-05-31 20:07:19.002200 WARNING matsalsdimmer: Unexpected error running initialize() for matsalsdimmer
2022-05-31 20:07:19.002375 WARNING matsalsdimmer: ------------------------------------------------------------
2022-05-31 20:07:19.002712 WARNING matsalsdimmer: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/app_management.py", line 163, in initialize_app
    await init()
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 103, in initialize
    await self.init()
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 147, in init
    )
  File "/config/appdaemon/apps/controllerx/cx_core/type_controller.py", line 66, in init
    await super().init()
  File "/config/appdaemon/apps/controllerx/cx_core/release_hold_controller.py", line 19, in init
    async def init(self) -> None:
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 118, in init
    default_actions_mapping = self.get_default_actions_mapping(self.integration)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 236, in get_default_actions_mapping
    raise ValueError(f"This controller does not support {integration.name}.")
ValueError: This controller does not support mqtt.
2022-05-31 20:07:19.002886 WARNING matsalsdimmer: ------------------------------------------------------------

- I tried in 4.19.0, but it didn't help. So maybe it was in 4.18.2 it worked?

Kind regards
