### ISSUE TITLE
[BUG] [zha] Unable to process different ZHA args

### ISSUE THREAD

**Issue by sreknob** [xaviml/controllerx#33]
# Bug report

## Description

Hi Xavi -

I have a SmartThings button that I have hanging around that I use with NodeRED and I thought, now that custom controller support is added, I should integrate it into ControllerX. Anyway, I found that the `zha.py` integration does not play nice as the `args` structure is different with this controller vs. the Ikea ones.

I added a `samin.py` file to cover the controller for light and media, but it didn't work as expected when using zha. After looking at the integration it appears that it was getting confused with the args. I'm hoping you can think of a way to make processing of ZHA args more robust to encompass a broad range of controllers, using this one as an example.

I've made a PR that works around it by excluding the commands from args processing, but it's a total hack and needs a better solution.

## Additional information

* Devices involved:
  * Model: [ eg. IKEA 1744 ] as [ Light | Media Player | Controller ]
  * ...
* Integration: Choose from `zha`
* AppDaemon version: [ v4.0.1 ]
* ControllerX version: [ v2.3.0b5 ]
* HACS version (if installed from there): [ v0.21.5 ]
* Home Assistant Core version: [ v0.105.4 ]

## AppDaemon app configuration

N/A

## ZHA Logs

These are the three events fired for the Samjin Button so you can see the structure

Single Press
```
{
    "event_type": "zha_event",
    "data": {
        "unique_id": "28:6d:97:00:01:04:4a:a9:1:0x0500",
        "device_ieee": "28:6d:97:00:01:04:4a:a9",
        "endpoint_id": 1,
        "cluster_id": 1280,
        "command": "button_single",
        "args": {
            "press_type": "single",
            "command_id": 0,
            "args": [
                1,
                0,
                0,
                0
            ]
        }
    },
    "origin": "LOCAL",
    "time_fired": "2020-02-22T02:02:08.079362+00:00",
    "context": {
        "id": "3aa8b5d8183240eabea80082b46729d9",
        "parent_id": null,
        "user_id": null
    }
}
```
Double Press
```
{
    "event_type": "zha_event",
    "data": {
        "unique_id": "28:6d:97:00:01:04:4a:a9:1:0x0500",
        "device_ieee": "28:6d:97:00:01:04:4a:a9",
        "endpoint_id": 1,
        "cluster_id": 1280,
        "command": "button_double",
        "args": {
            "press_type": "double",
            "command_id": 0,
            "args": [
                2,
                0,
                0,
                0
            ]
        }
    },
    "origin": "LOCAL",
    "time_fired": "2020-02-22T02:02:09.849708+00:00",
    "context": {
        "id": "28fe8cd893c4441cbb4ee07fb9220c8f",
        "parent_id": null,
        "user_id": null
    }
}
```
Long Press/Hold
```
{
    "event_type": "zha_event",
    "data": {
        "unique_id": "28:6d:97:00:01:04:4a:a9:1:0x0500",
        "device_ieee": "28:6d:97:00:01:04:4a:a9",
        "endpoint_id": 1,
        "cluster_id": 1280,
        "command": "button_hold",
        "args": {
            "press_type": "hold",
            "command_id": 0,
            "args": [
                3,
                0,
                0,
                0
            ]
        }
    },
    "origin": "LOCAL",
    "time_fired": "2020-02-22T02:02:11.973167+00:00",
    "context": {
        "id": "dd74314b28e6438b8a02a9dba4ff75ff",
        "parent_id": null,
        "user_id": null
    }
}

```

## Additional Context

I've filed a PR (#34) so you can see what I've done.

**Comment by xaviml** [comment]
I commented in #34 the changes and how this got fixed. I will let you know when there is a beta release, so you can check it out.

**Comment by xaviml** [comment]
Hi @sreknob 

There is a new beta release v2.3.0b6. You can check out the changes I mentioned in #34 and check the integration works. You can see the documentation for it in [here](https://xaviml.github.io/controllerx/controllers/IM6001-BTP01).

Thanks,
Xavi M.

**Comment by xaviml** [comment]
I will close the issue again once it is confirmed on your side that is fixed as well.

**Comment by sreknob** [comment]
Just tested both light and media player with zha and working after the changes in #37 
Can close this once #37 is integrated.
Amazing work Xavi 🥇

**Comment by xaviml** [comment]
Thanks @sreknob. Merged in dev.
