### ISSUE TITLE
Support for Light Group integration from HA

### ISSUE THREAD

**Issue by xaviml** [xaviml/controllerx#330]
# Feature Request

### Is your feature request related to a problem?

Light group integration does not work as expected in HA. It does not show the brightness and color_temp attribute at times. For this reason, ControllerX always supported Group integration. It was easy to understand if an entity was a group since the entity always starts with "group.".

### Describe the solution / feature you'd like

All group entities (Light group or Group integration) exposes an entity_id attribute with the list of entities that the entity controls. We would like ControllerX to detect such attribute, so Light Group integration could also work with ControllerX despite its buggy behavior.

### Describe alternatives you've considered

Users up until now have been using group integration, but that is just a work around to the full solution.

### Additional context

This issue would solve problems from #121, #295, #316, #319, and probably more that I have missed.

**Comment by bartplessers** [comment]
Thanx for implementation!

**Comment by xaviml** [comment]
Hi @bartplessers,

You can now dowload the latest beta version v4.14.0b0, and see if that works well for you.

Thanks,
Xavi M.

**Comment by xaviml** [comment]
This has been released in ControllerX [v4.14.0](https://github.com/xaviml/controllerx/releases/tag/v4.14.0). You can read more about it in the release note.
