### ISSUE TITLE
[BUG] Cannot run app installed via HACS running on hass.io

### ISSUE THREAD

**Issue by chbndrhnns** [xaviml/controllerx#35]
# Bug report

## Description

After installing controllerx via HACS and restarting my appdaemon installation (running in hass.io), I see this error listed below.

## Additional information

* Devices involved:
  * Model: [ eg. IKEA 1744 ] as [ Light | Media Player | Controller ]
  * ...
* Integration: deconz
* AppDaemon version: v4.0.1
* ControllerX version: v2.2.1
* HACS version (if installed from there): v0.21.5
* Home Assistant Core version: [ eg. v0.105.4 ]

## AppDaemon app configuration

```yaml
bathroom_controller:
  module: controllerx
  class: HueDimmerController
  controller: 0d74e3aef3bb4f569e40eb8da7d20555
  integration: deconz
  light: light.bulb_bathroom```

## Logs

```text
2020-02-22 17:52:00.328668 WARNING bathroom_controller: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 820, in check_app_updates
    await self.init_object(app)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 271, in init_object
    modname = await utils.run_in_executor(self, __import__, app_args["module"])
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/controllerx/controllerx.py", line 7, in <module>
    from devices.ikea import *
ModuleNotFoundError: No module named 'devices'
```

## Additional Context

Add any other context or screenshots about the bug here.

**Comment by xaviml** [comment]
Hi @chbndrhnns, looks like this is a bug from HACS 0.21.0 and 0.21.1. I just downloaded ControllerX from HACS 0.21.5 and I could not reproduce it. Could you maybe do the following:
- Make sure you have HACS v0.21.5
- Reinstall HACS
- Restart HA
- Uninstall ControllerX
- Install ControllerX
- Restart AppDaemon addon/server

Does the error keep appearing then?

Thanks,
Xavi M.

**Comment by chbndrhnns** [comment]
Your instructions fixed my problem. I would assume, however, that for AppDaemon apps, no restart of either HA nor AppDaemon should be necessary.

**Comment by xaviml** [comment]
That is partially right. ControllerX is shipped with non Automation python files and those are not reimported, but rather ignored. This is why AppDaemon addon/server needs to be restarted every time a new ControllerX version is installed, otherwise it will not get the new changes.
