### ISSUE TITLE
[FEATURE REQUEST] Enable GitHub Sponsors

### ISSUE THREAD

**Issue by tioan** [xaviml/controllerx#351]
Please enable GitHub Sponsors for your account @xaviml

**Comment by xaviml** [comment]
Hi @tioan,

Thank you for reaching out :) I will work in setting it GitHub Sponsors. In the meantime, you can support my work here https://www.buymeacoffee.com/xaviml.

Regards,
Xavi M.

**Comment by xaviml** [comment]
Hi @tioan,

I've enabled GitHub Sponsors: https://github.com/sponsors/xaviml/

Thank you for the suggestion :)

**Comment by tioan** [comment]
![image](https://user-images.githubusercontent.com/259990/131755635-6535eaef-6c37-4c6c-bf41-c46caf32b7f4.png)
Thx

**Comment by xaviml** [comment]
Thank you @tioan for your support! :)
