### ISSUE TITLE
[NEW DEVICE] Support for Sengled E1E-G7F

### ISSUE THREAD

**Issue by StudioShemp** [xaviml/controllerx#355]
# New Device Support

## Device Information

- Device Model: Sengled E1E-G7F
- Device Description: Sengled Smart Light Switch
- Device Manufacturer: Sengled

Hi Xavi, 

I've created a working sengled.py for Z2M for the Sengled E1E-G7F switch:
#Code as follows

```
from cx_const import DefaultActionsMapping, Light
from cx_core import LightController


class E1EG7FController(LightController):
    # Different states reported from the controller:
    # on, off, on_long, off_long, up, down
    

    def get_z2m_actions_mapping(self) -> DefaultActionsMapping:
        return {
            "on": Light.ON,
            "up": Light.CLICK_BRIGHTNESS_UP,
            "on_long": Light.HOLD_BRIGHTNESS_UP,
            "down": Light.CLICK_BRIGHTNESS_DOWN,
            "off_long": Light.HOLD_BRIGHTNESS_DOWN,
            "off": Light.OFF,
        }
```

#### Notes
on release z2m logs :
payload '{"action":"","linkquality":70}'
I'm not sure it's required - it works well without. 

There's a decent image at https://cdn.shopify.com/s/files/1/1176/7612/products/switch_1024x1024.png

I hope this is useful.

Cheers,
StudioShemp

**Comment by StudioShemp** [comment]
Hi,

Just an update. Contrary to what it says here: https://www.zigbee2mqtt.io/devices/E1E-G7F.html  the device exposes additional button-presses beyond on, up, down, off, on_double, on_long, off_double, off_long. The full repertoire is  on, off, on_long, off_long, up, down, up_long, down_long, on_double, off_double

I've ammended the code to use the long-press up/down as below:

```
from cx_const import DefaultActionsMapping, Light
from cx_core import LightController

class E1EG7FController(LightController):
# Different states reported from the controller:
# on, off, on_long, off_long, up, down, up_long, down_long, on_double, off_double

def get_z2m_actions_mapping(self) -> DefaultActionsMapping:
    return {
        "on": Light.ON,
        "up": Light.CLICK_BRIGHTNESS_UP,
        "up_long": Light.HOLD_BRIGHTNESS_UP,
        "down": Light.CLICK_BRIGHTNESS_DOWN,
        "down_long": Light.HOLD_BRIGHTNESS_DOWN,
        "off": Light.OFF,
    }
```

Cheers,

Alan

**Comment by xaviml** [comment]
Hi @StudioShemp,

If I understand correctly, this device does not have a "release" action for the hold button, right? In that case, is not recommended to use the "HOLD_*" actions.

I will integrate this controller and let you know of the default mapping if that makes sense to you.

Regards,
Xavi M.

**Comment by xaviml** [comment]
Hi @StudioShemp,

This is the proposed mapping: https://github.com/xaviml/controllerx/blob/e3b3d1c945beae4291bed2466bdca08a7e557cc9/apps/controllerx/cx_devices/sengled.py

Documentation yaml can be found here: https://github.com/xaviml/controllerx/blob/e3b3d1c945beae4291bed2466bdca08a7e557cc9/docs/_data/controllers/E1EG7F.yml

**Comment by StudioShemp** [comment]
Thanks @xaviml, 

that's correct - no release action is logged. Your mapping makes much more sense.

Thanks so much for getting this device supported. 

Cheers,
StudioShemp

**Comment by xaviml** [comment]
Hi @StudioShemp,

This device has been added to [ControllerX v4.16.0](https://github.com/xaviml/controllerx/releases/tag/v4.16.0).

Regards,
Xavi M.
