### ISSUE TITLE
[QUESTION] about color_temp attribute being present but not being read.

### ISSUE THREAD

**Issue by niek1992** [xaviml/controllerx#360]
# Question about color_temp attribute being present but not being read.

Hello, really cool project and have been using it for 6 months now without issue. But now i've got issues with changing colours with my Ikea E1810 controller via ControllerX. Started happening after a reboot of the HA host. I assume because ControllerX got updated. Already did some troubleshooting and tried some stuff but not successfull thus far. Have some questions:
* Is it possible to downgrade ControllerX version;
* How do i disable auto-update of ControllerX version;
* How do i get changing colours working again.

## Additional information

* Devices involved:
  * Model: IKEA E1810 as controller
  * Model: 2x IKEA LED1923R5 as Gu10 bulbs
  
* Integration: **Z2M**
* AppDaemon version: **4.1.0**
* ControllerX version: **v4.16.0**
* HACS version (if installed from there): **1.15.2**
* Home Assistant Core version: core-**2021.3.4**

## AppDaemon app configuration

```yaml
---
# old configuration, randomly stopped working after something updated
#studyroom_controller:
#  module: controllerx
#  class: E1810Controller
#  controller: sensor.ikea_tradfri_wireless_dimmer_upstairs_action
#  integration: z2m
#  light: group.studyroom_lights
#  transition: 200
#  steps: 50

# New configuration where i switched to Entity-Groups according to FAQ#4. 
studyroom_controller:
  module: controllerx
  class: E1810Controller
  controller: sensor.ikea_tradfri_wireless_dimmer_upstairs_action
  integration: z2m
  light: light.studyroom_lights
  transition: 200
  steps: 50
```

## Logs

```text
2021-09-22 12:26:45.921341 WARNING studyroom_controller: ------------------------------------------------------------
2021-09-22 12:26:45.921039 WARNING studyroom_controller: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 812, in async_worker
    await funcref(
  File "/config/appdaemon/apps/controllerx/cx_core/integration/z2m.py", line 66, in state_callback
    await self.controller.handle_action(new)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 352, in handle_action
    await self.call_action(action_key, extra=extra)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 426, in call_action
    await self.action_timer_callback({"action_key": action_key, "extra": extra})
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 464, in action_timer_callback
    await task
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 482, in call_action_types
    await action_type.run(extra=extra)
  File "/config/appdaemon/apps/controllerx/cx_core/action_type/predefined_action_type.py", line 118, in run
    await action(*positional, **action_args)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 64, in _action_impl
    await method(controller, *args, **kwargs)
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 679, in click
    attribute = await self.get_attribute(attribute)
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 583, in get_attribute
    if await self.is_color_supported():
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 564, in is_color_supported
    return len(COLOR_MODES.intersection(await self.supported_color_modes)) > 0
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 556, in supported_color_modes
    raise ValueError(
ValueError: `supported_color_modes` could not be read from `light.studyroom_lights(['light.ikea_tradfri_gu10_bulb1', 'light.ikea_tradfri_gu10_bulb2'])`. Entity might not be available.

```

## Additional Context

So after i found out that changing colours somehow didn't work anymore i investigated why by analysing the AppDaemon log. Found out that somehow ControllerX couldn't read the supported color modes from the group i created. I initially had it configured as a group and was working flawlessly:

```yaml
#################################################################
## Groups
#################################################################
# Commented because of ControllerX FAQ#4. Randomly color modes not working, but brightness does.
#studyroom_lights:
#  - light.ikea_tradfri_gu10_bulb1
#  - light.ikea_tradfri_gu10_bulb2
```

But saw FAQ#4 that it isn't supported so i modified it per FAQ#4:

```yaml
- platform: group
  name: studyroom_lights
  entities:
    - light.ikea_tradfri_gu10_bulb1
    - light.ikea_tradfri_gu10_bulb2
``` 

Unfortunately still didn't work. Verified that Colour Temperature is being exposed by the group and indeed it was. It also was exposed with the old configuration. If i looked up the group in Lovelace it allowed me to set the Colour Temperature at the group level, both lights changed colour. I then verified the states the current group exposed:

```yaml
min_mireds: 250
max_mireds: 454
effect_list:
  - channel_change
  - stop_effect
  - breathe
  - finish_effect
  - okay
  - blink
brightness: 175
color_temp: 250
entity_id:
  - light.ikea_tradfri_gu10_bulb1
  - light.ikea_tradfri_gu10_bulb2
friendly_name: studyroom_lights
icon: 'mdi:lightbulb-group'
supported_features: 47
```

Looking through the sourcecode of ControllerX, it throws that error because it can't find the value of attribute "supported_color_modes", which is assigned "color_temp" at line [#71](https://github.com/xaviml/controllerx/blob/14654cc09c20674d18f6f454fc0d45627c45a32d/apps/controllerx/cx_core/type/light_controller.py#L79). My lightgroup publishes color_temp, but it still throws that error. Brightness is unaffected though. 

For now i just don't control temperature with my E1810 controller, but manually via HA. Would like to use the E1810 controller though. So if you have any idea's, need more logfiles or debugging info please let me know.

Niek.

**Comment by niek1992** [comment]
What i could maybe do is switch the positions of `bulb1` with `bulb2` as to try if that fixes the issue with reading the attributes. Although i wonder if this fixes it though, because in HA i am able to control temperature at group level.

**Comment by xaviml** [comment]
Hi @niek1992,

Thank you for opening this issue and the thorough detail. First of all, sorry for this inconvenience, but the problem you have is because of an incompatible version. Home Assistant changed how the support feature worked for light integration. So I had to change the ControllerX to be compatible with the latest version of HA without being backwards compatible since the change is quite big on HA side. This change happened in HA 2021.4.0, and the ControllerX version supporting this change is v4.15.0, in fact, you can read this in the [release notes](https://github.com/xaviml/controllerx/releases/tag/v4.15.0).

> Is it possible to downgrade ControllerX version;

Yes, this is totally possible through HACS. You can go to `/hacs/automation` where ControllerX is present. Then click in the three dots menu from ControllerX and select `Reinstall`. A pop-up will appear and you will be able to change your ControllerX version. Then just click on `Install` and finally restart the AppDaemon addon/server.

> How do i disable auto-update of ControllerX version;

I am not sure how you are getting auto updates of ControllerX. If you are using HACS, this is all managed from HACS and as far as I know HACS does not allow auto-updates, or at least I could not see any option for this. HACS will warn you of a new ControllerX version, but you have to go and click update manually to install the new version.

> How do i get changing colours working again.

You have 2 options. Either you upgrade to Home Assistant >= 2021.4.0, or downgrade ControllerX (with the steps I mentioned in your first question) to 4.14.0.

I hope this helps you understand your situation and how you can solve your problem. Again, sorry for the inconvenience, but since ControllerX depends on AppDaemon, Home Assistant, different devices, different integrations, I cannot ensure the code works always for all versions of what it depends on. So my statement is to support always the latest stable version of each dependency.

Regards,
Xavi M.

**Comment by niek1992** [comment]
Hey @xaviml, 

Thanks for the response, i actually might have updated ControllerX after i've read the release notes for it but kinda forgot about it :). I'll plan an upgrade for HA Core this weekend, i could downgrade but then i'd be running into the same issues once i upgrade Core. 

> Yes, this is totally possible through HACS. You can go to /hacs/automation where ControllerX is present. Then click in the three dots menu from ControllerX and select Reinstall. A pop-up will appear and you will be able to change your ControllerX version. Then just click on Install and finally restart the AppDaemon addon/server.

Ofcourse, how did i forget about selecting branch versions when (re-)installing.

> I hope this helps you understand your situation and how you can solve your problem. Again, sorry for the inconvenience, but since ControllerX depends on AppDaemon, Home Assistant, different devices, different integrations, I cannot ensure the code works always for all versions of what it depends on. So my statement is to support always the latest stable version of each dependency.

No problem, i already think that its awesome that you've written this and made it public for others to use. i can only dream of writing something like this. Thanks for responding to me, i'll mark it as solved as you've basically gave me all the answers i needed. Upgrade Core, or downgrade ControllerX

Thanks!
