### ISSUE TITLE
Support for Niko91004 with z2m

### ISSUE THREAD

**Issue by kris10an** [xaviml/controllerx#364]
# New Device Support

## Device Information

- Device Model: Niko91004
- Device Description: Niko dimmer switch for Hue system
- Device Manufacturer: Niko

#### Actions

Button | Click | Hold | Release
-- | -- | -- | --
Top left (A0) | recall_scene_0<br>recall_scene_4 | recall_scene_0 | recall_scene_4
Bottom left (A1) | recall_scene_1<br>recall_scene_5 | recall_scene_1 | recall_scene_5
Top right (B0) | recall_scene_3<br>recall_scene_7 | recall_scene_3 | recall_scene_7
Bottom right (B1) | recall_scene_2<br>recall_scene_6 | recall_scene_2 | recall_scene_6
Top both | press_2_of_2<br>release_2_of_2 | press_2_of_2 | release_2_of_2
Bottom both | press_1_of_2<br>release_1_of_2 | press_1_of_2 | release_1_of_2

#### Notes

Please consider adding support for z2m with this controller. Please let me know if more info is needed or how I can contribute.

**Comment by kris10an** [comment]
Just found out that release [1.21.2 of z2m](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.21.2), issued a couple of days ago changes the actions. 

Button | Click | Hold | Release
-- | -- | -- | --
Top left (A0) | press_1<br>release_1 | press_1 | release_1
Bottom left (A1) | press_2<br>release_2 | press_2 | release2
Top right (B0) | press_3<br>release_3 | press_3 | release_3
Bottom right (B1) | press_4<br>release_4 | press_4 | release_4
Top both | press_1_and_3<br>release_1_and_3 | press_1_and_3 | release_1_and_3
Bottom both | press_2_and_4<br>release_2_and_4 | press_2_and_4 | release_2_and_4

In addition there's an action ‘press_energy_bar’

**Comment by xaviml** [comment]
I will close this ticket for now. If something else needs to be discussed, please open a new ticket.
