### ISSUE TITLE
[FEATURE REQUEST] Stop a cover that has no state reporting with one click after an open/close command has been sent. (Ikea 1743 Remote / Somfy IO Shutters))

### ISSUE THREAD

**Issue by jaddel** [xaviml/controllerx#368]
# Feature Request

### Is your feature request related to a problem?

I'm always frustrated that I have to hold_release my cover remotes when I want to stop a cover in a certain position.

### Describe the solution / feature you'd like

When ever I press a remote to open/close a cover the app/automation saves the last command and starts a timer for a configurable amount of time e.g the maximum time the cover need's to close. If now in the defined timeframe the same button is pressed again it will default to e.g `cover.stop_cover`.
The timer is needed if one want's to fully close/open the cover and later on uses a different way to open it, so that on the next use the remote will sent an open / close command again and not `cover.stop_cover`.

**Comment by xaviml** [comment]
Hi @jaddel,

Thank you for opening this issue. First of all, if you want to open a cover and stop it, you can either hold (as you mention) or click twice as long it is using the `toggle_open` and `toggle_close` [predefined actions](https://xaviml.github.io/controllerx/advanced/predefined-actions#cover).

Secondly, you can already achieve this behaviour with the `delay` [action type](https://xaviml.github.io/controllerx/advanced/action-types). For example, you could do the following with the E1743 controller:

```yaml
example_app:
  module: controllerx
  class: E1743CoverController
  integration: z2m
  controller: sensor.my_controller_action
  mapping:
    "on":
      - open
      - delay: 5 # Wait 5 seconds
      - stop
    "off": [close, {delay: 5}, stop] # You can also abbreviate like this
```

Obviously, you will need to configure how many seconds you want to wait until it stops after open/close.

Would this suit your needs?

Regards,
Xavi M.

**Comment by jaddel** [comment]
> Secondly, you can already achieve this behaviour with the `delay` [action type](https://xaviml.github.io/controllerx/advanced/action-types). For example, you could do the following with the E1743 controller:
> 
> ```yaml
> example_app:
>   module: controllerx
>   class: E1743CoverController
>   integration: z2m
>   controller: sensor.my_controller_action
>   mapping:
>     "on":
>       - open
>       - delay: 5 # Wait 5 seconds
>       - stop
>     "off": [close, {delay: 5}, stop] # You can also abbreviate like this
> ```
> 
> Obviously, you will need to configure how many seconds you want to wait until it stops after open/close.
> 
> Would this suit your needs?

I think to use toggle_open/close could be a good workaround for now.

For the second example you gave I'm not sure if you got me correct. If I read it right this is a sequence that gets fired once on / off is received. 
What I had in mind was that the mapping for e.g on/off changes for a defined timeframe and reverts after that.

Would that also be possible?

**Comment by xaviml** [comment]
Hi @jaddel,

Let me see if I understand your use case correctly. You would like to open and close a cover with just a single button controller (or with just one button from one controller with multiple buttons). Then, let's imagine the following scenario:

- The previous action was to close the cover, and the cover is already not moving.
- You press the button.
- The cover opens (because the previous action was to close).
- While the cover is opening, you press the button, and the cover stops.
- After the cover stopped, you press the button and the cover closes (because the previous action was to open).
- You leave the cover open for 3 or 4 hours.
- You come again and press the button.
- The cover closes.

Is this sequence correct and what you would like to have? If so, I can help you out with the configuration for such a use case. Also, in this case, there is no need to configure a timing because the covers (normally) have the following states:
- opened
- closed
- opening
- closing

So, if the state is opening or closing, ControllerX would know if it is moving or not, so it can be stopped.

Regards,
Xavi M.

**Comment by jaddel** [comment]
I just tried this configuration but it's not doing anything.

```
living_room_shade:
  module: controllerx
  class: E1743CoverController
  controller: 58:8e:81:ff:fe:30:4a:ff
  integration: zha
  cover_duration: 30
  cover: cover.living_room_shades
```

What is strange that I have this in the logs even though there is no app configured with that name atm.

```
2021-10-30 22:00:19.311749 INFO AppDaemon: Initializing app office_shade2 using class E1743StatelessCoverController from module controllerx
2021-10-30 22:00:19.313432 WARNING AppDaemon: Unable to find class E1743StatelessCoverController in module controllerx - 'office_shade2' is not initialized
```

**Comment by jaddel** [comment]
I just double checked the remote via zha_event in the developer section. 
For some reason it wasn't working. 

I'll check it again with a working remote and report back.

**Comment by xaviml** [comment]
Hi @jaddel,

It looks like the appdaemon logs do not match that configuration. The app is called living_room_shade, and there is no E1743StatelessCoverController class.

Regards,
Xavi M.

**Comment by jaddel** [comment]
> Hi @jaddel,
> 
> It looks like the appdaemon logs do not match that configuration. The app is called living_room_shade, and there is no E1743StatelessCoverController class.
> 
> Regards, Xavi M.

yes I know, but I still had that entry in the logs which did't make any sense since it wasn't configured. 
Anyhow... :)

Today I restarted the host and now everything works as expected. 

Thank you very much for adding this!
