### ISSUE TITLE
[FEATURE REQUEST] Default AppDaemon start-up behavior when toggling brightness

### ISSUE THREAD

**Issue by JDFS404** [xaviml/controllerx#388]
# Feature Request

### Describe the solution / feature you'd like

I restart my Docker apps every night due to backups and such. So to change the default behavior when starting AppDaemon would be nice (i.e. always brightness first go ```down``` and then go ```up```). Reason for asking: I have an automatic adaptive lighting integration, but I notice that sometimes I dim the lights because they're too bright. I almost never make them brighter!

**Comment by xaviml** [comment]
Hi @JDFS404,

Thank you for the feature request. I have added this to [ControllerX v4.18.0](https://github.com/xaviml/controllerx/releases/tag/v4.18.0).

Regards,
Xavi M.
