### ISSUE TITLE
[QUESTION] multiple clicks not working on E1810Controller

### ISSUE THREAD

**Issue by lkeijser** [xaviml/controllerx#392]
# Question

I'm trying to get the multi-click option working on the IKEA E1810 controller, but so far I've not been successful. Perhaps I've made a silly mistake. If anyone could take a look, I'd appreciate it.

## Additional information

* Devices involved:
  * IKEA E1810

* Integration: deconz
* AppDaemon version: 4.1.1
* ControllerX version: 4.16.0
* HACS version: 1.15.2
* Home Assistant Core version: core-2021.11.5

## AppDaemon app configuration

```yaml
tradfri-douche:
  module: controllerx
  class: E1810Controller
  controller: douchelamp_afstandsbediening
  integration: deconz
  light: light.color_temperature_light_6
  #supported_features: 35
  merge_mapping:
    toggle$3:
      service: scene.turn_on
      data:
        entity_id: scene.dolly_modus
```

## Logs
Double clicking the toggle (biggest middle) button only results in turning it on/off:

```text
🤖 Service: light.toggle
  - entity_id: light.color_temperature_light_6
2021-11-29 13:10:37.507010 INFO tradfri-douche: 🎮 Button event triggered: `1002`
2021-11-29 13:10:37.516135 INFO tradfri-douche: 🏃 Running `Predefined (toggle)` now
2021-11-29 13:10:37.527598 INFO tradfri-douche: 
🤖 Service: light.toggle
  - entity_id: light.color_temperature_light_6
2021-11-29 13:10:41.009299 INFO tradfri-douche: 🎮 Button event triggered: `1002`
2021-11-29 13:10:41.020688 INFO tradfri-douche: 🏃 Running `Predefined (toggle)` now
2021-11-29 13:10:41.033380 INFO tradfri-douche: 
🤖 Service: light.toggle
  - entity_id: light.color_temperature_light_6
```

## Additional Context
N/A

**Comment by xaviml** [comment]
Hi @lkeijser,

If you are using deCONZ integration, you should be using the deCONZ events (1000, 1002, etc). You can see the events of your controller in the device page under the deCONZ section: https://xaviml.github.io/controllerx/controllers/E1524_E1810#deconz

The configuration you are looking for would be:

```yaml
tradfri-douche:
  module: controllerx
  class: E1810Controller
  controller: douchelamp_afstandsbediening
  integration: deconz
  light: light.color_temperature_light_6
  #supported_features: 35
  merge_mapping:
    1002$3:
      service: scene.turn_on
      data:
        entity_id: scene.dolly_modus
```

Regards,
Xavi M.

**Comment by lkeijser** [comment]
Aaaaaah, thank you so much! Works like a charm.
