### ISSUE TITLE
Help setting up Zigbee2MQTT, an Ikea E1744LightController to control an Ikea Symfonisk speaker

### ISSUE THREAD

**Issue by pabutterworth** [xaviml/controllerx#440]
Hi,

I'm not sure what I've done wrong, but I can't seem to get this to respond at all!

I installed the AppDaemon 4, and its running. I installed ControllerX in HACS and disabled legacy mode.

I have the following in my /config/appdaemon/apps/apps.yaml, I cant see where the configuration page is, is this what I'm missing?

kitchen_sonos_controller:
  module: controllerx
  class: E1744MediaPlayerController
  controller: sonos_remote
  integration: z2m
  media_player: kitchen

And it does nothing at all. What have I missed? How do I diagnose this, ControllerX looks to be exactly what I want, i want to remove these brand-specific Zigbee hubs.

Thanks
Paul

**Comment by xaviml** [comment]
Glad you got it sorted. Closing the ticket. Thanks!
