### ISSUE TITLE
Use of IKEA Gateway?

### ISSUE THREAD

**Issue by andreacampanella** [xaviml/controllerx#450]
# Feature Request

### Is your feature request related to a problem?

If so, then add a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Comment by andreacampanella** [comment]
Sorry, opened by mistake, would you mind delete it?

**Comment by xaviml** [comment]
Hi @andreacampanella,

Yes, I will close ticket.

Thank you,
