### ISSUE TITLE
[BUG] 1744 configured through ZHA randomly stopped working

### ISSUE THREAD

**Issue by spencertiedge** [xaviml/controllerx#465]
# Bug report

## Description

I have a 1744 remote that I've been using to control a Sonos media player. It is configured as a Media Player remote through the zha integration. It has worked flawlessly for nearly a year and suddenly is only responding to single clicks. I can see the rotation is registering in AppDaemon logs, but volume control does not work. Additionally, cannot use double / triple click to change tracks, and double/triple click does not register in AppDaemon logs.

## Additional information

Devices involved:
  - Model: IKEA 1744 as Media Player
- Integration: zha
- AppDaemon version: v.0.8.2
- ControllerX version: v4.18.2
- HACS version (if installed from there): v1.24.5
- Home Assistant Core version: 2022.4.5

## AppDaemon app configuration

```office_controller:
  module: controllerx
  class: E1744MediaPlayerController
  controller: xxx
  integration: zha
  volume_steps: 25
  media_player: media_player.office
```

## Logs

```
2022-04-18 21:16:04.313010 INFO office_controller: 🎮 Button event triggered: `toggle`
2022-04-18 21:16:04.322259 INFO office_controller: 🏃 Running `Predefined (play_pause)` now
2022-04-18 21:16:04.340074 INFO office_controller: 
🤖 Service: media_player.media_play_pause
  - entity_id: media_player.office
2022-04-18 21:17:01.212999 INFO office_controller: 🎮 Button event triggered: `stop`
2022-04-18 21:17:01.226040 INFO office_controller: 🏃 Running `Predefined (release)` now
2022-04-18 21:17:01.713035 INFO office_controller: 🎮 Button event triggered: `stop`
2022-04-18 21:17:01.723318 INFO office_controller: 🏃 Running `Predefined (release)` now
```

## Additional Context

Add any other context or screenshots about the bug here.

**Comment by xaviml** [comment]
Hi @spencertiedge ,

This seems to be related to #455 and #457. It has been fixed in the development branch and it has been pushed to the beta release.

Could you please enable beta release in HACS and download v4.19.0b3?

Regards,
Xavi M.

**Comment by spencertiedge** [comment]
> Hi @spencertiedge ,
> 
> This seems to be related to #455 and #457. It has been fixed in the development branch and it has been pushed to the beta release.
> 
> Related comment about E1744: [#457 (comment)](https://github.com/xaviml/controllerx/issues/457#issuecomment-1098273593)
> 
> Could you please enable beta release in HACS and download v4.19.0b3?
> 
> Regards, Xavi M.

Thanks for the quick response -- can confirm after updating to v4.19.0b3, everything is working as intended. Apologies for making a duplicate post and not seeing the related issues. Thanks much!
