### ISSUE TITLE
Support for Climate Control?

### ISSUE THREAD

**Issue by sabaatworld** [xaviml/controllerx#473]
I'm thinking of using controllerx to control climate devices like my AC using the IKEA 5 button controller. Something like:

Right Arrow: Heat
Left Arrow: Cool
Increase Brightness: Target temperature + 1
Decrease Brightness: Target temperature - 1
Toggle / Middle button: Off

Sure I could call services to do this but having this supported natively would be nice. Would controllerx accept a pull request for this feature or has plans to support this in the near future?

**Comment by xaviml** [comment]
Hi @sabaatworld,

This is totally possible. If you want to draft a PR, this is what needs to be done:
- Create Controller type (climate_controller.py) in `apps/controllerx/cx_core/type`. You use `switch_controller.py` as a template.
- Add the actions in `apps/controllerx/cx_const.py` for the new controller type (`class Climate`).
- Create a new controller in `apps/controllerx/cx_devices/ikea.py` (E1810ClimateController) with the default mapping you would like to give to this controller.
- Add new controller documentation in `docs/_data/controllers/E1524_E1810.yml`.

If you have docker in your machine, you can run the following to test your code:

```shell
docker run \
-v $PWD/apps/controllerx:/usr/src/app/conf/apps/controllerx \
-v $PWD/apps.yaml:/usr/src/app/conf/apps/apps.yaml \
--rm -e DASH_URL=http://127.0.0.1:5050 \
-e HA_URL="http://YOUR_HA_IP:8123" \
-e TOKEN="YOUR_HA_TOKEN" \
acockburn/appdaemon:latest
```

You will need `apps.yaml` file at the root of the project. However, this will not work with MQTT integration or z2m with `listen_to: mqtt`. I will add this in the CONTRIBUTING.md file now.

Regards,
Xavi M.

**Comment by xaviml** [comment]
I added the following section in the CONTRIBUTING.md file: https://github.com/xaviml/controllerx/blob/dev/CONTRIBUTING.md#run-code-with-appdaemon

**Comment by xaviml** [comment]
Closing ticket for now. Happy to reopen it again for further discussion.
