### ISSUE TITLE
Add support for IKEA E2001/E2002 (zha)

### ISSUE THREAD

**Issue by Langthjem** [xaviml/controllerx#504]
# New Device Support

## Device Information

- Device Model: E2001/E2002
- Device Description: IKEA STYRBAR remote control
- Device Manufacturer: IKEA

#### Actions

- `on`: Sent when button `brightness_up` is pressed
- `off`: Sent when button `brightness_down` is pressed
- `brightness_up`: Sent when button `brightness_up` is held
- `brightness_down`: Sent when button `brightness_down` is held
- `color_up`: Sent when button `right` is pressed
- `hold_color_up`: Sent when button `right` is held
- `hold_color_down`: Sent when button `left` is held

**Comment by xaviml** [comment]
Hi @Langthjem ,


Thabk you fir opening this issue. Could you please share a ZHA event as an example?

Regards,
Xavi M.

**Comment by Langthjem** [comment]
Hi @xaviml ,

actually just created the issue to have something to bind my PR to. Already created the integration based on E1810. Difference seems to be no TOGGLE and SYNC, but instead ON  and OFF.

`Event 1 sent 11.23:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "cc:86:ec:ff:fe:6a:a1:ce",
        "unique_id": "cc:86:ec:ff:fe:6a:a1:ce:1:0x0006",
        "device_id": "9bc1c8ffd96af2a125996ea7f1eed2d8",
        "endpoint_id": 1,
        "cluster_id": 6,
        "command": "off",
        "args": [],
        "params": {}
    },
    "origin": "LOCAL",
    "time_fired": "2022-06-06T09:23:08.491702+00:00",
    "context": {
        "id": "01G4W56FJBTYPBCHY3V5B8M9XM",
        "parent_id": null,
        "user_id": null
    }
}
Event 0 sent 11.23:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "cc:86:ec:ff:fe:6a:a1:ce",
        "unique_id": "cc:86:ec:ff:fe:6a:a1:ce:1:0x0006",
        "device_id": "9bc1c8ffd96af2a125996ea7f1eed2d8",
        "endpoint_id": 1,
        "cluster_id": 6,
        "command": "on",
        "args": [],
        "params": {}
    },
    "origin": "LOCAL",
    "time_fired": "2022-06-06T09:23:06.337392+00:00",
    "context": {
        "id": "01G4W56DF1NF3517XJCP42SXBW",
        "parent_id": null,
        "user_id": null
    }
}`

**Comment by xaviml** [comment]
This issue can now be closed. As an action from it, it has been decided to rename `W2049` controller to `E2002` since it is the official name.
