### ISSUE TITLE
[QUESTION] E2002LightController

### ISSUE THREAD

**Issue by esteban-uo** [xaviml/controllerx#514]
# Question

Dear @xaviml,
I have a configuration so:

```yml
livingroom_controller:
  log_level: DEBUG
  module: controllerx
  class: E2002LightController
  controller: automation.controller_1
  integration: zha
  light: light.lamp_1
```

whenever I press any button with the automation.controller_1, the lamp_1 is not being triggered. I see in the logs this:

```
DEBUG livingroom_controller: `click_color_down` is not recognized as a template
DEBUG livingroom_controller: `click_color_up` is not recognized as a template
DEBUG livingroom_controller: `hold_brightness_up` is not recognized as a template
DEBUG livingroom_controller: `hold_brightness_down` is not recognized as a template
DEBUG livingroom_controller: `hold_color_down` is not recognized as a template
DEBUG livingroom_controller: `hold_color_up` is not recognized as a template
DEBUG livingroom_controller: `release` is not recognized as a template
INFO livingroom_controller: Previous message repeated 1 times
```

Could you give me a hint on what am I doing wrong? many thanks!

## Additional information

- Devices involved:
- Model: [ Remote Control N2 IKEA (STYRBAR) ] as [ Controller ]
- Integration: Choose from `zha`

**Comment by xaviml** [comment]
Hi @esteban-uo ,

The controller `automation.controller_1` is not expected in that configuration. ZHA expects a unique IEEE. Please check here how to extract the value of your device:

https://xaviml.github.io/controllerx/others/extract-controller-id/#zha

Regards,
Xavi M.

**Comment by esteban-uo** [comment]
> Hi @esteban-uo ,
> 
> The controller `automation.controller_1` is not expected in that configuration. ZHA expects a unique IEEE. Please check here how to extract the value of your device:
> 
> https://xaviml.github.io/controllerx/others/extract-controller-id/#zha
> 
> Regards, Xavi M.

Hi Xavi, 

That was the problem, many thanks!! kudos for your work :)
