### ISSUE TITLE
Add support for deCONZ to Philips929002398602

### ISSUE THREAD

**Issue by Jano1959** [xaviml/controllerx#516]
# New Device Support
## Device Information

- Device Model: RWL022
- Device Description: Philips929002398602  ( https://xaviml.github.io/controllerx/controllers/Philips929002398602/ )
- Device Manufacturer: Philips
DeConz API info:
{
.... {
        "attr": {
...
            "manufacturername": "Signify Netherlands B.V.",
            "modelid": "RWL022",
            "name": "fitness_switch_02",
            "swversion": "2.44.0_hBB3C188",
            "type": "ZHASwitch",
            "uniqueid": .......
        },
        "e": "changed",
        "id": "68",
        "r": "sensors",
        "t": "event",
        "uniqueid": ....
    }
}

## Integrations
?

### Integration:  
DeConz

#### Actions
on_press_release		1000 (0 sec) & 1002 (0 sec)
on_hold					1001 (8 sec)
on_hold_release			1003

up_press_release		2000 (0 sec) & 2002 (0 sec)
up_hold					2001 (8 sec)
up_hold_release			2003

down_press_release		3000 (0 sec) & 3002 (0 sec)
down_hold				3001 (8 sec)
down_hold_release		3003

off_press_release		4000 (0 sec) & 4002 (0 sec)
off_hold  				4001 (8 sec)
off_hold_release		4003

(x sec) = ( Eventduration )

Sometimes the x002 comes before the x000 when xxxx_press_release.

**Comment by xaviml** [comment]
Hi @Jano1959 ,

Thank you for creating this ticket. Knowing that this controller is an improved version of the Hue Dimmer, could you try if your controller works with `HueDimmerController` class? That class supports deCONZ. It seems to be the same mapping. If so, I will be copying the same mapping for this controller. It is just to confirm the mapping.

Thank you!

**Comment by Jano1959** [comment]
Worked like a charm :) 

Why didn't I think of that....

**Comment by xaviml** [comment]
Thank you @Jano1959 , sorry I did not mention it earlier... I will add the same mapping then. In the meantime, you can use HueDimmer.

Cheers,

**Comment by xaviml** [comment]
Hi @Jano1959 ,

I just released [ControllerX v4.22.0b0](https://github.com/xaviml/controllerx/releases/tag/v4.22.0b0) with the support of deCONZ for Philips929002398602. Please, let me know if it is working as expected for you. You can download from HACS by enabling "beta versions" when downloading ControllerX. If you already have it, you need to click on "Redownload" option for ControllerX in HACS.

Regards,
Xavi M.

**Comment by xaviml** [comment]
This device support for deCONZ has been added to [ControllerX v4.22.0](https://github.com/xaviml/controllerx/releases/tag/v4.22.0).
