### ISSUE TITLE
Friends of Hue Battery buttons

### ISSUE THREAD

**Issue by fribse** [xaviml/controllerx#528]
# New Device Support

## Device Information

- Device Model: friends_of_hue_switch
- Device Description: FUGA style button with 4 buttons, battery driven
- Device Manufacturer: smartkontakten.dk

#### Actions

The button numbers are distributed like this

1  3
2  4

The number is put in below to get the actions :-)

Bt x
Click x000 release after short click x002
Hold x000 holding x001 release x003

#### Notes

An event from HA
```
{
    "event_type": "deconz_event",
    "data": {
        "id": "friends_of_hue_switch",
        "unique_id": "00:00:00:00:01:71:7f:b8",
        "event": 2002,
        "device_id": "cc8b2b102fce1d045a50c22aa1c297ae"
    },
    "origin": "LOCAL",
    "time_fired": "2022-07-12T18:12:09.629459+00:00",
    "context": {
        "id": "01G7SSS0RXKTPM1VPRPRGEBYG2",
        "parent_id": null,
        "user_id": null
    }
}
```

![20220712_202216](https://user-images.githubusercontent.com/13660621/178566796-cda83214-4aea-446c-9809-d530dc42491b.JPG)
![20220712_202210](https://user-images.githubusercontent.com/13660621/178566818-cff875c0-6f9a-4d27-82ef-2e4f65c2d340.JPG)

**Comment by fribse** [comment]
I think I made it work with these mappings:

```
office_sofa_hue:
  module: controllerx
  class: E1743Controller
  controller: office_sofa_multi_control
  integration: deconz
  light: light.office_sofa
  mapping:
    1002: "on"
    1001: hold_brightness_up
    1003: release
    3002: "off"
    3001: hold_brightness_down
    3003: release

office_ceiling_hue:
  module: controllerx
  class: E1743Controller
  controller: office_sofa_multi_control
  integration: deconz
  light: light.office_ceiling
  mapping:
    2002: "on"
    2001: hold_brightness_up
    2003: release
    4002: "off"
    4001: hold_brightness_down
    4003: release
```

**Comment by xaviml** [comment]
Hi @fribse ,

Thank you for opening this issue. The mapping you provided will be enough for the implementation, and thank you for the working configuration as example, it will definitely help.

It might take me some time to have this done, but I will keep you updated.

Regards,
Xavi M.

**Comment by xaviml** [comment]
The support for this device has been added to a new beta version, [ControllerX v4.23.0b0](https://github.com/xaviml/controllerx/releases/tag/v4.23.0b0). You can now download it from HACS by enabling the beta versions.

**Comment by fribse** [comment]
Great, I hope it's supported in z2m integration as well, as I'm moving there currently :-)

**Comment by fribse** [comment]
Ah, I found the code in the debug.
press_1-4
release_1-4
Now I just need to find the 'hold', or find out how that is accomplished :-)

**Comment by xaviml** [comment]
Hi @fribse ,

Could you send me the device page from Zigbee2MQTT documentation?

Regards,
Xavi M.

**Comment by xaviml** [comment]
Thanks!

This controller is supported by ControllerX: https://xaviml.github.io/controllerx/controllers/PTM215X/

As you discovered, Zigbee2MQTT does not support the hold actions, only deCONZ. Not sure what is the context on not supporting it.

Regards,
Xavi M.

**Comment by fribse** [comment]
Ok, gotcha. Weird that it doesn't, oh well, I'll live with it.
Thankyou very much for all your help, and before I moved it to z2m, the beta version worked fine in deconz for this button set :-)
