### ISSUE TITLE
Cant add repo to HACS 

### ISSUE THREAD

**Issue by Ronnie-J** [xaviml/controllerx#55]
# Bug report

## Description

Trying to add repo (https://github.com/xaviml/controllerx) to HACS but it fails.

```
An error ocoured while processing
Exception: HacsException
Message: Repostitory structure for v2.3.1 is not compliant
Could not add this repository, make sure it is compliant with HACS.
```

## Additional information

HACS 0.23.1

**Comment by xaviml** [comment]
Hi @Ronnie-J

Did you try to add ControllerX as a custom repository?

You can find it under the "APPDAEMON APPS" tab on HACS.

**Comment by sreknob** [comment]
@Ronnie-J - ControllerX is part of the [default repos in HACS](https://github.com/hacs/default), there should be no need to add it as a custom repo. I suspect this might have to do with HACS handling of repos already in the default list. I know there is some logic in there to remove repos from the custom list when they get added as default.
Search ControllerX under the Appdaemon Apps tab in HACS to find it.

**Comment by Ronnie-J** [comment]
@xaviml @sreknob interesting - I dont have a `Appdaemon Apps` tab under HACS. Only `Integrations`, `Plugins` etc. I tried adding the relevent config in yaml according to https://hacs.xyz/docs/categories/appdaemon_apps but it does not seem to be a problem with your repo then I guess. I'll try and fix HACS first and then try to fetch it from there - for now I fetched it manually - thanks

**Comment by Ronnie-J** [comment]
Had to remove HACS and add it again to enable the menu. It works now, thanks!
