### ISSUE TITLE
Aqara Opple WXCJKG11LM

### ISSUE THREAD

**Issue by Debug1Bug** [xaviml/controllerx#553]
# New Device Support

## Device Information

- Device Model: Aqara Opple WXCJKG11LM
- Device Description: Two button light controller
- Device Manufacturer: Aqara

#### Actions

- `button_1_press`: 1002
- - `button_2_press`: 2002
- `button_1_hold`: 1001
- - `button_2_hold`: 2001
- - `button_1_release after hold`: 1003
- - `button_2_release after hold`: 2003

**Comment by xaviml** [comment]
The support for this device has been added to a new beta version, [ControllerX v4.23.0b0](https://github.com/xaviml/controllerx/releases/tag/v4.23.0b0). You can now download it from HACS by enabling the beta versions.

**Comment by Debug1Bug** [comment]
Thank you. Appreciate it.

**Comment by xaviml** [comment]
This device is now ready to be used in [ControllerX v4.23.0](https://github.com/xaviml/controllerx/releases/tag/v4.23.0). I will mark this issue as closed.
