### ISSUE TITLE
[BUG] ICTCG1Controller/Z2M reporting "brightness" instead of "rotate"

### ISSUE THREAD

**Issue by ghiglie** [xaviml/controllerx#577]
# Bug report

As per title, the IKEA  via Z2M  integration is reporting with "brighteness" instead of rotate, e.g.: "brightness_move_down"

## Additional information

- Devices involved:
  - Model: IKEA ITTC-G-1 as Controller 
  - Model: Yeeligh Mono6 as Light
- Integration: z2m
- AppDaemon version: [ v4.2.1 ]
- ControllerX version: [ v4.23.0 ]
- HACS version (if installed from there): [ v1.27.2 ]
- Home Assistant Core version: [ 2022.9.5 ]

## AppDaemon app configuration

```yaml
garage_controller:
  module: controllerx
  class: ICTCG1Controller
  integration: z2m
  controller: remote_dimmer_action
  light: light.yeelight_mono6_0x000000000e366b0a```

**Comment by xaviml** [comment]
Hi @ghiglie ,

Thank you for opening this issue. May I know if you have the `legacy: false`  attribute for this device in Zigbee2mqtt?

Regards,
Xavi M.

**Comment by ghiglie** [comment]
Hello @xaviml !
You're right, I have the "legacy" parameter set to false (by UI). 

I set that on all devices, following the hint on UI  - Set to false to disable the legacy integration (highly recommended), will change structure of the published payload (default true)".

I cant' test right now the "true" setting, but it's not a problem keeping it like that.

**Comment by xaviml** [comment]
Hi @ghiglie ,

No, no need to change that. I have the policy to stick always to the mapping for `legacy: false` since that is what is recommended from Zigbee2MQTT documentation.

I will change the mapping for this controller.

Regards,
Xavi M.

**Comment by ghiglie** [comment]
Thanks Xavi!
