### ISSUE TITLE
[NEW DEVICE] Zigbee2Mqtt seems to have changed Xiaomi WXKG07LM actions.

### ISSUE THREAD

**Issue by SergioRius** [xaviml/controllerx#584]
# New Device Support

## Device Information

- Device Model: WXKG07LM
- Device Description: Xiaomi 2 rocker battery wall switch
- Device Manufacturer: Xiaomi

#### Actions

Before, actions where:
right, right_double, right_long
left, left_double, left_long
....

Now have changed to:
single_right, double_right, hold_right
single_left, double_left, hold_left
single_both, double_both, hold_both

#### Notes

The device page in the Z2M database seems to ha recently been modified and reflects the new actions. I can't fetch the old contents, though.
![imagen](https://user-images.githubusercontent.com/1693727/193271689-f390c1e3-9277-4d02-aec4-ccb22c2b6435.png)

I've noticed this because I had to re-pair all the devices after a gateway change. Before, they where paired using the old actions, but after the re-pair, those Aqara switches didn't work anymore so I debugged the actions published and after changing them for the controllerx apps that do merge_mapping, they worked.
But default mappings should be changed in code. I don't feel confident enough to do a pull request on this as I'm unsure where to find all the related code. Only found the one relative to the last ZM change.

**Comment by xaviml** [comment]
Hi @SergioRius ,

Thank you for opening this issue :) I just created and merged this PR with the fix: https://github.com/xaviml/controllerx/pull/587

I will be releasing the fix soon, but in the meantime, you can map those actions with `mapping` or `merge_mapping` as you mentioned.

Regards,
Xavi M.

**Comment by SergioRius** [comment]
Your welcome. I'm so sorry for not requesting a PR myself.
I've already installed the latest beta version and checked that those changes work properly. Thank you.

**Comment by xaviml** [comment]
Hi @SergioRius ,

This device mapping is now fixed in [ControllerX v4.24.0](https://github.com/xaviml/controllerx/releases/tag/v4.24.0).

Regards,
Xavi M.
