### ISSUE TITLE
[QUESTION] Using HueDimmerController to toggle HA scenes with on button

### ISSUE THREAD

**Issue by johnneerdael** [xaviml/controllerx#621]
# Question

Current setup:
livingroom:
  module: controllerx
  class: HueDimmerController
  controller: 00:17:88:01:08:07:e6:45
  integration: zha
  light: light.living_room_lights

However I have different scenes that I know control using my apple watch and would like to control them using the remote to by cycling the on button.

I see the support is there but I'm just not sure where to get started is this correct when using deconz? It would be helpful if a scene example is added to the examples pages since the only one we currently have is one for a none standard controller I believe:

livingroom:
  module: controllerx
  class: HueDimmerController
  controller: 00:17:88:01:08:07:e6:45
  integration: zha
  light: light.living_room_lights
  mapping:
    1002:
      scene1:  scene.cozy_living_room
      scene2: scene.puzzling
      scene3: scene.puzzling_guests

**Comment by johnneerdael** [comment]
livingroom:
  module: controllerx
  class: HueDimmerController
  controller: 00:17:88:01:08:07:e6:45
  integration: zha
  light: light.living_room_lights
  mapping:
    on_short_release:
      scene1: scene.cozy_living_room
      scene2: scene.puzzling
      scene3: scene.puzzling_guests

I've built it like this since I'm using zha for the controller (through deconz) but it broke the controller fully :D

**Comment by inertia666** [comment]
I think you need to setup an input helper with a dropdown in HA.

The link here basically does the same thing but you can write the scene ID in the helper and then use the service to call the correct scene.

https://github.com/xaviml/controllerx/issues/610

**Comment by xaviml** [comment]
I hope I resolved this question. Please, feel free to reopen it if not resolved. Or open a new one :)

Thank you!
