### ISSUE TITLE
Allow controlling outlets

### ISSUE THREAD

**Issue by Crocmagnon** [xaviml/controllerx#65]
# Allow controlling outlets

### Describe the solution / feature you'd like

I'd like to control outlets as easily as lights

Meaning the config snippet should be as small as possible if I just want to map the on/off buttons of my remote to the outlet.

### Describe alternatives you've considered

Though I haven't tried yet, I guess this can be achieved more verbosely with a custom controller calling services.

### Additional context

The IKEA smart outlet (fr: https://www.ikea.com/fr/fr/p/tradfri-prise-connectee-20364476/) is cheap and can be bought with a E1743 switch.
It's exposed as a switch in home assistant.

It would be nice to load all these devices in ZHA and pair them with controllerx.

I don't know how hard it would be, but I'm willing to contribute, if someone could point me in the right direction for where to start! 😀

**Comment by xaviml** [comment]
Hi @Crocmagnon,

What you are mentioning is something I had in mind and this is why I created ControllerTypes. This controllers have to define a domain that will be working with. For now I have the `light` and the `media_player`. The idea is to add a new ControllerType `SwitchController` and then create a `E1743SwitchController` that will give a default behaviour to the `E1743` controller from IKEA to turn on and off switches. Will this meet your requirements or you were pointing to another direction?

However, as you are saying, it can already be used with `CallServiceController`, but you will need to manually map the actions and there are no default behaviours.

I will keep this issue so you can test the code once is done if you are willing to test. Thank you :)
