### ISSUE TITLE
Add support for Prolight 5412748727388 (Zigbee2MQTT) 

### ISSUE THREAD

**Issue by Theoreet** [xaviml/controllerx#657]
**New Device Support**

Device Information
Device Model: Prolight 5412748727388
Device Manufacturer: Prolight

**Integrations**
Integration: z2m
**Actions**
Mapping can be found here: https://www.zigbee2mqtt.io/devices/5412748727388.html

**Comment by xaviml** [comment]
This device can be now tested on [ControllerX v4.25.0b0](https://github.com/xaviml/controllerx/releases/tag/v4.25.0b0).

**Comment by xaviml** [comment]
This device is now available on [ControllerX v4.25.0](https://github.com/xaviml/controllerx/releases/tag/v4.25.0). This issue can be now closed. If any bugs are found related to this issue, please open a new one.
