### ISSUE TITLE
IKEA TRADFRI E1745/E1525 motion sensor

### ISSUE THREAD

**Issue by Crocmagnon** [xaviml/controllerx#67]
# New Device Support

## Device Information

* Device Model: E1745/E1525
* Device Description: IKEA TRADFRI E1745/E1525 motion sensor
* Device Manufacturer: IKEA

##### Device state
The device has 2 buttons, each one with 2 states:
- `day/night` : either `sun` or `moon`
- `full/low` : either `full` or `low` (30%) (only for E1745)
- `timer`: any value between 60 and 600, represents the time in seconds the light should remain on (only for E1525)

##### Events
Two type of events can be sent:
Command : `on_with_timed_off`, args:
* `[0, xx, 0]`: Sent when a movement has been detected and the light needs to be turned on (either because `day/night == sun` or `day/night == moon` and not enough light)
* `[1, xx, 0]`: Sent when a movement has been detected and the light **does not need** to be turned on (because `day/night == moon` and there is enough light)

See the notes for the `xx` value.

When `full/low == low`, before sending the `turn on the light event` (`on_with_timed_off` with `[0, xx, 0]`), another event is sent:
command: `move_to_level_with_on_off`, args: `[76, 1]`

##### Summary
To replicate the behavior when paired with the IKEA gateway:
* when receiving `on_with_timed_off` with `[1, xx, 0]`, do nothing.
* when receiving `on_with_timed_off` with `[0, xx, 0]`, turn on the light at the desired level and start a timer for 1800s to turn off the light if there hasn't been any other movement.
* when receving `move_to_level_with_on_off` with `[76, 1]`, set `brightness` to `76` for the next turn on (or change the brightness if light is on) (only for E1745).
* when receiving another `on_with_timed_off` with `[0, xx, 0]` during the timer, reset the timer.

#### Notes

The E1745 is a newer version. From what I observed, it sends events on a less regular basis (once every ~100 seconds vs once every second).
The E1525 does not support low light but supports a customizable timer on the back of the device (between 60 and 600 seconds). This value will be reflected in the second argument. The value is always 1800 for E1745 which does not support customizing the timer.

E1745 docs: https://www.ikea.com/fr/fr/manuals/tradfri-detecteur-de-mouvement-sans-fil__AA-2145280-2_pub.pdf

Since the E1745 does not support customizing the "on" duration, the adapter should be configurable to use either the 1800s from the payload or an override from the configuration. Since the E1745 only sends events once every ~100s, we might want to either restrict the override value or at least log a warning when setting a value lower than this threshold: the light might blink.

**Comment by Crocmagnon** [comment]
Added notes about the turn off timer.

**Comment by Crocmagnon** [comment]
Added info about E1525

**Comment by Crocmagnon** [comment]
Since this implementation will likely be based on timers, we should be able to pass a list of controllers for a single application since we will need to access the stored timer to reset it when a new movement event is observed.

**Comment by Crocmagnon** [comment]
I have a basic implementation for one sensor and one light : https://gist.github.com/Crocmagnon/4df32b0e209a39edf53556497f598e23, with a sample config: https://gist.github.com/Crocmagnon/c35553aa6597acad71de6c4334460362

My use case involves restricting the time when the sensor might turn the light on, so there are some sections about that in the gist.

**Comment by xaviml** [comment]
Hi @Crocmagnon, sorry for the delay. If I understand, you would like to add the motion sensor as a new device in ControllerX, right? Although I could add a motion sensor to control a light, the `LightController` is made to control lights with a remote/controller, to dim the lights or change the color or color temp.

From what I understand, you would like to add the motion sensor to give it the same functionality it has with the Tradfri IKEA hub, right? Even though you are right about ControllerX trying to give the same behaviour you lose when not using the original hub, it is just bounded to controllers and remotes acting to different entities (light, media player and with your PR now switches).

I am not closed to doing changes to integrate sensors, however, for the moment I am just integrating controllers. I invite you to take a look to [Automoli](https://github.com/benleb/ad-automoli) which allows you to bind motion sensors with lights in a smart manner. Maybe @benleb might be able to help you better and explain if Automoli would suit your use case if he is willing to.

Thanks for your interest :)

**Comment by Crocmagnon** [comment]
Thanks for pointing me to AutoMoLi, I wasn't aware of this project!
I'll check to see if it fits my needs :)
