### ISSUE TITLE
Any woes with the new AppDaemon 0.13?

### ISSUE THREAD

**Issue by fribse** [xaviml/controllerx#850]
# Question

Before I update the appdaemon I just wanted to find out if there are any known issues with it?

**Comment by xaviml** [comment]
Hi @fribse ,

These are my reasons about updating:
- The update is just a minor update for the addon (without changing anything from AppDaemon code)
- I have not received any complaints about it.
- I have updated it and I have not had any issues.

If you decide to update, please make sure to create snapshot of the previous version, so you can rollback.

If you have any issues, please let me know.

Thank you,
Xavi M.

**Comment by fribse** [comment]
Thanks!
