### ISSUE TITLE
Can multiple clicks be registered with E1743Controller?

### ISSUE THREAD

**Issue by hoof** [xaviml/controllerx#876]
This is not an issue - just to be clear. Maybe only related to the documentation in such a case :) 
I have difficulties understanding [Advanced Config/Multiple Clicks](https://xaviml.github.io/controllerx/advanced/multiple-clicks/) specifically the part about managing multiple clicks "especially for those single click events":

Does it mean a "counter" is always present, and so even buttons without support for multiple clicks are supported (Like the E1743)? If so how's the syntax? Tried different combos with the "on" action and the new token `$` - however all unsuccessful. 

Thanks! 

BR Hoof

**Comment by sreknob** [comment]
@hoof - I think that the special actions of ON and OFF need to be enclosed in quotes, so the format of the configuration might be the problem. Can you post your configuration?

My understanding is that counters are only present when there is mapping that contains the token ```$```, at which point waits the ```multiple_click_delay``` after a mapped event that contains the token.

Have you tried using

```
mapping:
  "on"$2: "your desired action here"
```

**Comment by xaviml** [comment]
Hi @hoof ,

That is correct, the multiclick functionality is available for any controller. It is a layer that ControllerX controls on top of your controller. I will revisit documentation to make this more clear.

Thank you :)
