### ISSUE TITLE
[NEW DEVICE] IKEA Somrig/rodret

### ISSUE THREAD

**Issue by Stianker1** [xaviml/controllerx#885]
# New Device Support

## Device Information

- Device Model: [ eg. E2213 ]
- Device Description: [ eg. IKEA somrig wireless dimmer ]
- Device Manufacturer: [ eg. IKEA ]

#### Actions

- `button_xyz_press`: Sent when button xyz is pressed
- `button_xyz_hold`: Sent when button xyz is held

**Comment by m4dm4xi** [comment]
I would also be interested in this.

This is the zigbee2mqtt device page: https://www.zigbee2mqtt.io/devices/E2213.html

**Comment by VS-X** [comment]
Rodret is basically identical to E1743 as far as actions are concerned. You can use `E1743Controller` class to make it work.
Somrig sends completely different actions, so it would require larger changes.

**Comment by Hans-0** [comment]
E1743Controller Doesn’t work for the IKEA RODRET

**Comment by mortelil** [comment]
Hello!
I also want support for this device. My local IKEA has plenty of them, seems this is the new cheap switch I will use around the house going forward. I have one so far, let me know if there's something I can do to help out to get this supported.

**Comment by xaviml** [comment]
Hi all. Thank you for the interactions in this issue, and sorry for the late reply.

Could someone confirm if the actions issued by Somrig are the ones sepcfied in Z2M documentation?

1_initial_press, 2_initial_press, 1_long_press, 2_long_press, 1_short_release, 2_short_release, 1_long_release, 2_long_release, 1_double_press, 2_double_press.

If so, could someone hint what the actions should be for those events? Or at least mention when they are triggered?

Regards,
Xavi M.

**Comment by xaviml** [comment]
This feature has been added to ControllerX beta release [v4.27.0b0](https://github.com/xaviml/controllerx/releases/tag/v4.27.0b0).

**Comment by xaviml** [comment]
This feature has been added to ControllerX beta release [v4.27.0](https://github.com/xaviml/controllerx/releases/tag/v4.27.0).

**Comment by bakeromso** [comment]
> Rodret is basically identical to E1743 as far as actions are concerned. You can use `E1743Controller` class to make it work. Somrig sends completely different actions, so it would require larger changes.

Thank you for this! This made it work for me. I want to add it back in the documentation somewhere, should I change E1743 entry into E1743/E2201 ? (E2201 is the Rodret as you said)
