### ISSUE TITLE
[BUG] ControllerX refuses to Install

### ISSUE THREAD

**Issue by JohnMcIl** [xaviml/controllerx#886]
# Bug report

## Description

ControllerX fails to install and load to AppDaemon. I have read ALL the documentation thoroughly including installing AppDaemon properly via HACS. 

### Errors with ControllerX Install locations
I have NFI what is going on but it sounds like it is not installing properly to the AppDaemon folder.

I have read:
https://www.reddit.com/r/homeassistant/comments/17xzfj3/cant_find_appdaemonyaml_configuring_addon_in_ui/
https://xaviml.github.io/controllerx/start/installation/
https://github.com/xaviml/controllerx/issues/875
https://community.home-assistant.io/t/appdaemon-new-config-location-issue/674558/4
Which I have done - see screenshot.
![Screenshot 2024-02-02 at 1 07 21 pm](https://github.com/xaviml/controllerx/assets/3096550/b7bc2901-60b9-4599-8a06-73ccca668e1f)

**Comment by xaviml** [comment]
Hi @JohnMcIl ,

Sorry for the late reply. I hope the workarounds you specified worked for you. I am planning on documenting the new way of installing and updating ControllerX, but I do not have a clear answer yet.

Regards,
Xavi M.

**Comment by JohnMcIl** [comment]
Nope I used a different solution.

Best wishes,





John McIlveen

**Comment by xaviml** [comment]
Thank you @JohnMcIl. I have updated the preview docs for now with the new installation steps.

https://controllerx.netlify.app/controllerx/start/installation/

Hope this will clarify doubts that you and other might have with the changes around AppDaemon addon.

Thanks.
