### ISSUE TITLE
[QUESTION] Z31BRL support for Z2M

### ISSUE THREAD

**Issue by 88fingerslukee** [xaviml/controllerx#888]
Hey all, I love ControllerX!!!! Thank you so much!

Request for you, can you help enable support for the Z31BRL with Z2M and not just deconz?  Is there something that limits the ability of this?  Any help would be incredibly appreciated.

thanks!
88

**Comment by 88fingerslukee** [comment]
@xaviml are you still maintaining this app?

**Comment by xaviml** [comment]
Hi @88fingerslukee ,

Sorry for the late reply. I have been busy lately and I could not pay much attention to this project. My intention is to come back more active and keep maintaining ControllerX.

As per your question, this controller could be supported by ControllerX for z2m. All we need is the specification, so if you have one, please create a new GitHub issue of type "New device" and fill in the form.

https://github.com/xaviml/controllerx/issues/new?assignees=xaviml&labels=new-device&projects=&template=new_device.md&title=%5BNEW+DEVICE%5D

Regards,
Xavi M.

**Comment by xaviml** [comment]
This ticket can be now closed since #958 is now open.
