### ISSUE TITLE
[NEW DEVICE] WXKG12LM deconz

### ISSUE THREAD

**Issue by phdelodder** [xaviml/controllerx#90]
# New Device Support

## Device Information

* Device Model: [ WXKG12LM ]
* Device Description: [ Xiaomi Aqara wireless switch ]
* Device Manufacturer: [ Xiaomi ]

## Integrations

If possible, provide the event mappings for the different actions that can be performed on the controller. Specify the integration.

If you can provide mappings for multiple integrations, copy the section below as many times as needed.

#### Actions

* `button_1_press`: 1002
* `button_1_double_press`: 1004
* `button_1_hold`: 1001
* `button_1_release_after_hold`: 1003
* `button_1_shake`: 1006

**Comment by xaviml** [comment]
Hi @phdelodder,

I just released v2.8.1 with the support for the xiaomi button for deCONZ integration. I also fixed the problem we discussed about the events from Hue Dimmer switch. Now the hold action should not turn off your light as it was doing before :)

Thanks,
Xavi M.
