### ISSUE TITLE
[NEW DEVICE] Z31BRL support for Z2M

### ISSUE THREAD

**Issue by 88fingerslukee** [xaviml/controllerx#958]
# New Device Support

## Device Information

- Device Model: Z31BRL 
- Device Description: Lutron Dimmer
- Device Manufacturer: Lutron

## Integrations

```
Z2M
```
#### Actions

- `'brightness_move_to_level'`: Sent when dial is turned either direction, the values go from 0-255. It gives a transition time of 2
- `brightness_move_to_level`: Sent when the button is pressed. It just changes the brightness from 0 to 255 and back to 0. So on or off.

**Comment by xaviml** [comment]
Hi @88fingerslukee ,

I see you put `brightness_move_to_level` twice. Is that a mistake? This device supports the following for deconz:
- Toggle
- Brightness up
- Brigntess down

I am guessing that brightness up and down is supported by `brightness_move_to_level`, but what about `toggle`?

Regards,
Xavi M.

**Comment by 88fingerslukee** [comment]
Xavi, when I press the button I don't see the toggle payload. It just uses the brightness set action and sets it to either 0 or 255. Unless I'm missing something?

**Comment by xaviml** [comment]
Hi @88fingerslukee ,

Okay, I understand now. I will modify PR and beta release it later today.

Regards,
Xavi M.

**Comment by xaviml** [comment]
Hi @88fingerslukee ,

I just released [v4.27.0b1](https://github.com/xaviml/controllerx/releases/tag/v4.27.0b1) with this controller. If you have some time to try, I would appreciate.

I will be doing the official release in some days, but this beta release can be used in the meantime.

Regards,
Xavi M.

**Comment by 88fingerslukee** [comment]
Thank you so much! I won't be able to test for a couple of weeks unfortunately, but I'll do it as soon as I possibly can.

**Comment by xaviml** [comment]
This feature has been added to ControllerX beta release [v4.27.0](https://github.com/xaviml/controllerx/releases/tag/v4.27.0).
